add: `pacstall-gui-git`
pacstall/pacstall-programs pull request #1005
Opened 2022-04-18 19:24 UTC by cat-master21

2022-04-18 20:20 UTC, Mar0xy commented on packages/pacstall-gui-git/pacstall-gui-git.pacscript
> +  sudo mv -f ./settings.sh ./disable-root-check.diff /usr/src/pacstall/pacstall-gui-git/usr/lib/pacstall-gui
```suggestion
  sudo mkdir /usr/src/pacstall/pacstall-gui-git/usr/lib/pacstall-gui
  sudo mv -f ./settings.sh ./disable-root-check.diff /usr/src/pacstall/pacstall-gui-git/usr/lib/pacstall-gui
```

2022-04-18 20:20 UTC, Mar0xy commented on packages/pacstall-gui-git/pacstall-gui-git.pacscript
> +          sudo chmod -R a+w /usr/lib/pacstall-gui
```suggestion
          sudo chmod -R a+w /usr/src/pacstall/pacstall-gui-git/usr/lib/pacstall-gui
```

2022-04-18 23:49 UTC, Henryws requested changes

2022-04-18 23:49 UTC, Henryws commented on packages/pacstall-gui-git/pacstall-gui-git.pacscript
> +  sudo mkdir -p "/usr/src/pacstall/pacstall-gui-git/usr/bin" "/usr/src/pacstall/pacstall-gui-git/usr/lib/pacstall-gui"
```suggestion
  sudo mkdir -p "${STOWDIR}/${name}/usr/bin" "${STOWDIR}/${name}/usr/lib/pacstall-gui"
```

2022-04-18 23:49 UTC, Henryws commented on packages/pacstall-gui-git/pacstall-gui-git.pacscript
> +  sudo install -Dm755 pacstall-gui /usr/src/pacstall/pacstall-gui-git/usr/bin/pacstall-gui
```suggestion
  sudo install -Dm755 pacstall-gui "${STOWDIR}/${name}/usr/bin/pacstall-gui"
```

2022-04-18 23:49 UTC, Henryws commented on packages/pacstall-gui-git/pacstall-gui-git.pacscript
> +  sudo mv -f ./settings.sh ./disable-root-check.diff /usr/src/pacstall/pacstall-gui-git/usr/lib/pacstall-gui
```suggestion
  sudo mv -f ./settings.sh ./disable-root-check.diff "${STOWDIR}/${name}/usr/lib/pacstall-gui"
```

2022-04-18 23:49 UTC, Henryws commented on packages/pacstall-gui-git/pacstall-gui-git.pacscript
> +  sudo install -Dm755 LICENSE /usr/src/pacstall/pacstall-gui-git/usr/share/licenses/pacstall-gui/LICENSE
```suggestion
  sudo install -Dm755 LICENSE "${STOWDIR}/${name}/usr/share/licenses/pacstall-gui/LICENSE"
```

2022-04-18 23:49 UTC, Henryws commented on packages/pacstall-gui-git/pacstall-gui-git.pacscript
> +          sudo chmod -R a+w /usr/src/pacstall/pacstall-gui-git/usr/lib/pacstall-gui
```suggestion
          sudo chmod -R a+w "${STOWDIR}/${name}/usr/lib/pacstall-gui"
```

2022-04-19 00:17 UTC, Henryws requested changes

2022-04-19 00:17 UTC, Henryws commented on packages/pacstall-gui-git/pacstall-gui-git.pacscript
> +
```suggestion

```

2022-04-19 00:19 UTC, Henryws approved these changes

2022-04-19 00:22 UTC, merged