add: `glow-deb`
pacstall/pacstall-programs pull request #1012
Opened 2022-04-21 09:55 UTC by mirenradia

## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [ ] Contact devs
- [x] Add maintainer to pacscript

2022-04-21 13:33 UTC, Henryws requested changes

2022-04-21 13:33 UTC, Henryws commented on packages/glow-deb/glow-deb.pacscript
> +
Remove this line

2022-04-21 13:37 UTC, mirenradia commented on packages/glow-deb/glow-deb.pacscript
> +
Done!

2022-04-21 13:47 UTC, Henryws requested changes
Add `breaks`

2022-04-21 13:52 UTC, mirenradia commented
> Add `breaks`

Can I add `replace` instead? I don't think this "breaks" any other pacstall package.

2022-04-21 13:53 UTC, Henryws commented
Sure

2022-04-21 13:58 UTC, Henryws requested changes

2022-04-21 13:58 UTC, Henryws commented on packages/glow-deb/glow-deb.pacscript
> +replace=${gives}
Quote this

2022-04-21 14:02 UTC, mirenradia commented on packages/glow-deb/glow-deb.pacscript
> +replace=${gives}
Ah yes. I missed that. Now fixed.

2022-04-22 02:40 UTC, Henryws approved these changes

2022-04-22 02:40 UTC, merged