add: `protonvpn-gui`
pacstall/pacstall-programs pull request #1014
Opened 2022-04-21 22:34 UTC by WRM-42

2022-04-22 23:28 UTC, Henryws requested changes

2022-04-22 23:28 UTC, Henryws commented on packages/protonvpn-gui/protonvpn-gui.pacscript
> +breaks="${name}-git"
```suggestion
breaks="${name}-git ${name}-bin"
```

2022-04-22 23:49 UTC, Henryws approved these changes

2022-04-23 01:31 UTC, Henryws requested changes
CI fails.

2022-04-23 02:06 UTC, WRM-42 commented
The error seems to be CI specific, everything works fine on a normal machine

https://packages.debian.org/buster/gir1.2-appindicator3-0.1

2022-04-23 02:48 UTC, cat-master21 commented
Because: https://www.debian.org/releases/bullseye/armhf/release-notes.en.pdf se section `5.3.1 Noteworthy obsolete packages` 

> The deprecated libappindicator libraries are no longer provided. As a result, the related pack-
>
>ages libappindicator1, libappindicator3-1 and libappindicator-dev are no longer
>available. This is expected to cause dependency errors for third-party software that still depends
>on libappindicator to provide system tray and indicator support.
the same issue with discord package.

2022-04-23 20:58 UTC, Henryws approved these changes

2022-04-23 20:58 UTC, merged