upd(obs-backgroundremoval): added repology
pacstall/pacstall-programs pull request #1061
Opened 2022-04-29 19:48 UTC by Zahrun

2022-04-30 22:40 UTC, Henryws requested changes

2022-04-30 22:40 UTC, Henryws commented on packages/obs-backgroundremoval/obs-backgroundremoval.pacscript
> +  cmake -j"$(nproc)" -DobsIncludePath=/usr/include/obs -DCMAKE_INSTALL_PREFIX:PATH="${STOWDIR}"/"${name}"/usr .. > /dev/null && cmake --build . -j"$(nproc)" > /dev/null
cmake doesn't recognize the `-j` flag

2022-05-07 09:59 UTC, Zahrun commented on packages/obs-backgroundremoval/obs-backgroundremoval.pacscript
> +  cmake -j"$(nproc)" -DobsIncludePath=/usr/include/obs -DCMAKE_INSTALL_PREFIX:PATH="${STOWDIR}"/"${name}"/usr .. > /dev/null && cmake --build . -j"$(nproc)" > /dev/null
Thank you

2022-05-07 10:01 UTC, Zahrun commented
Since https://github.com/royshil/obs-backgroundremoval/commit/cc9d4a5711f9388ed110230f9f793bb071577a23, the build fails. I commented to the author. Let’s wait for that to be fixed.

2022-05-07 10:23 UTC, Zahrun commented
Btw, the CI build fails but says success

2022-05-08 22:40 UTC, cat-master21 commented
Curious @Zahrun why is language-pack-en[-base] installed as it does almost nothing see [filelist](https://packages.ubuntu.com/jammy/all/language-pack-en-base/filelist) while Debian installs the needed mo file as it happens.

2022-05-10 09:52 UTC, Zahrun commented
Sorry all, I got confused between the `-git` version and this version.
This version compiles fine.

@cat-master21, indeed `language-pack-en` was not required and I could confirm the plugin works on debian too.

2022-05-12 00:30 UTC, Henryws commented
CI fails, look at the logs.

2022-05-12 03:56 UTC, Zahrun commented
> CI fails, look at the logs.

I committed again the same files, and it looks fine now

2022-05-12 04:25 UTC, Henryws requested changes

2022-05-12 04:25 UTC, Henryws commented on packages/obs-backgroundremoval/obs-backgroundremoval.pacscript
>        sudo apt install libsimde-dev
This should be appended to `depends`

2022-05-12 05:14 UTC, Zahrun commented on packages/obs-backgroundremoval/obs-backgroundremoval.pacscript
>        sudo apt install libsimde-dev
True, thank you

2022-05-13 03:35 UTC, merged