upd(pomatez-deb): added repology
pacstall/pacstall-programs pull request #1062
Opened 2022-04-29 19:51 UTC by Zahrun

2022-04-30 22:49 UTC, Henryws requested changes
Fails because of libappindicator

2022-05-07 10:32 UTC, Zahrun commented
> Fails because of libappindicator

Will work fine on:
Ubuntu [ [bionic](https://packages.ubuntu.com/bionic/libappindicator3-1)  ][  [bionic-updates](https://packages.ubuntu.com/bionic-updates/libappindicator3-1)  ] [  [focal](https://packages.ubuntu.com/focal/libappindicator3-1)  ] [  [impish](https://packages.ubuntu.com/impish/libappindicator3-1)  ] [  [jammy](https://packages.ubuntu.com/jammy/libappindicator3-1)  ] [  [kinetic](https://packages.ubuntu.com/kinetic/libappindicator3-1)  ]
Debian [  [stretch](https://packages.debian.org/stretch/libappindicator3-1)  ] [  [buster](https://packages.debian.org/buster/libappindicator3-1)  ]

Do we always need to support  bullseye ?

2022-05-07 13:30 UTC, Henryws commented
> > Fails because of libappindicator
> 
> Will work fine on: Ubuntu [ [bionic](https://packages.ubuntu.com/bionic/libappindicator3-1) ] [ [bionic-updates](https://packages.ubuntu.com/bionic-updates/libappindicator3-1) ] [ [focal](https://packages.ubuntu.com/focal/libappindicator3-1) ] [ [impish](https://packages.ubuntu.com/impish/libappindicator3-1) ] [ [jammy](https://packages.ubuntu.com/jammy/libappindicator3-1) ] [ [kinetic](https://packages.ubuntu.com/kinetic/libappindicator3-1) ] Debian [ [stretch](https://packages.debian.org/stretch/libappindicator3-1) ] [ [buster](https://packages.debian.org/buster/libappindicator3-1) ]
> 
> Do we always need to support bullseye ?

hmm, I guess we don't

2022-05-09 02:42 UTC, Henryws approved these changes

2022-05-09 02:43 UTC, merged