feat(adapta-gtk-theme-git): add `pkgver`
pacstall/pacstall-programs pull request #1103
Opened 2022-05-08 16:16 UTC by WRM-42

2022-05-08 22:34 UTC, Henryws requested changes

2022-05-08 22:34 UTC, Henryws commented on packages/adapta-gtk-theme-git/adapta-gtk-theme-git.pacscript
> +  sudo make install DESTDIR="/usr/src/pacstall/${gives}"
```suggestion
  sudo make install DESTDIR="${STOWDIR}/${name}"
```

2022-05-08 22:39 UTC, WRM-42 commented on packages/adapta-gtk-theme-git/adapta-gtk-theme-git.pacscript
> +  sudo make install DESTDIR="/usr/src/pacstall/${gives}"
1e3a288603144b86a7fd4524c4f63d84493d0ecd

2022-05-08 23:29 UTC, Henryws requested changes
Oops, look at the CI

2022-05-09 22:10 UTC, WRM-42 commented
@Henryws Adapta has not been maintained since at least 2018 by looking at the commits log. Wouldn't it be better to remove the package completely?

2022-05-09 23:11 UTC, Henryws commented
> @Henryws Adapta has not been maintained since at least 2018 by looking at the commits log. Wouldn't it be better to remove the package completely?

I've still seen people use it, so we should keep it.

2022-05-10 02:43 UTC, Henryws requested changes
Check the CI logs; something to do with a newline version

2022-05-28 20:56 UTC, Henryws approved these changes

2022-05-28 20:57 UTC, merged