add : jonaburg-picom-git
pacstall/pacstall-programs pull request #1186
Opened 2022-05-27 19:21 UTC by Ruturajn

- Adding `jonaburg-picom-git` to the list of supported packages.
- `jonaburg-picom-git.pacscript` has been added.
- The packagelist is also updated with `jonaburg-picom-git`.

I had a question, since picom has a config file, where do I put it, since it needs to be stowed. Please suggest.

Thanks

2022-05-27 19:36 UTC, Henryws commented
The config should not be included at all

2022-05-27 19:40 UTC, Ruturajn commented
Ok, so should I remove those lines regarding placing the config file from the pacscript?

2022-05-27 19:40 UTC, Henryws commented
> Ok, so should I remove those lines regarding placing the config file from the pacscript?

Yup

2022-05-27 19:41 UTC, Ruturajn commented
Ok, I'll make the changes and push them.

2022-05-27 19:48 UTC, Henryws requested changes

2022-05-27 19:48 UTC, Henryws commented on packages/jonaburg-picom-git/jonaburg-picom-git.pacscript
> +
These lines aren't needed

2022-05-27 19:48 UTC, Ruturajn commented on packages/jonaburg-picom-git/jonaburg-picom-git.pacscript
> +
Ok, I'll remove them.

2022-05-27 19:56 UTC, Henryws approved these changes

2022-05-28 19:51 UTC, merged

2022-05-28 20:03 UTC, Ruturajn commented
Hi, I wanted to add two more packages `ibhagwan-picom` and `qtile-extras` , so should I create a separate pull request for each one of them?

2022-05-28 20:04 UTC, Henryws commented
Make separate PRs please!

2022-05-28 20:05 UTC, Ruturajn commented
Ok, Thanks