add: `chwp-deb`
pacstall/pacstall-programs pull request #1410
Opened 2022-07-19 11:54 UTC by RouHim

Link to repo: https://github.com/RouHim/chwp

> Changes the wallpaper from the command line.

2022-07-19 13:53 UTC, Mar0xy requested changes

2022-07-19 15:01 UTC, Henryws requested changes

2022-07-19 15:01 UTC, Henryws commented on packages/chwp-deb/chwp-deb.pacscript
> +version="$(pkgver)"
Remove this and use `version="1.119.0`. (https://github.com/RouHim/chwp/releases/tag/v1.119.0)

2022-07-20 15:05 UTC, Henryws approved these changes

2022-07-20 15:05 UTC, merged