add: `monero-gui-git`
pacstall/pacstall-programs pull request #1439
Opened 2022-07-28 16:43 UTC by WRM-42

2022-08-01 17:03 UTC, Henryws commented
CI fails

2022-08-03 22:39 UTC, Henryws commented on packages/monero-gui-git/monero-gui-git.pacscript
> +    make devmode -j"$(nproc)"
Is `devmode` required?

2022-08-03 23:08 UTC, WRM-42 commented on packages/monero-gui-git/monero-gui-git.pacscript
> +    make devmode -j"$(nproc)"
Yes, otherwise it won't compile

2022-08-03 23:12 UTC, Henryws commented
So is devmode the compiled release version?

Sent from Proton Mail mobile

-------- Original Message --------
On Aug 3, 2022, 19:08, Béné wrote:

> @WRM-42 commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [packages/monero-gui-git/monero-gui-git.pacscript](https://github.com/pacstall/pacstall-programs/pull/1439#discussion_r937206584):
>
>> +depends="qtbase5-dev qtdeclarative5-dev qml-module-qtqml-models2 qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs qml-module-qtquick-xmllistmodel qml-module-qt-labs-settings qml-module-qt-labs-platform qml-module-qt-labs-folderlistmodel qttools5-dev-tools qml-module-qtquick-templates2 libqt5svg5-dev miniupnpc libunbound-dev graphviz doxygen libunwind8-dev libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libnorm-dev libusb-1.0-0-dev libpgm-dev libgcrypt20-dev"
> +breaks="${pkgname}-bin"
> +description="Open-source graphical user interface (GUI) wallet developed by the Monero community"
> +maintainer="WRM-42 ***@***.***>"
> +
> +pkgver() {
> +    git ls-remote "${url}" master | cut -f1 | cut -c1-8
> +}
> +version="$(pkgver)"
> +
> +prepare() {
> +    true
> +}
> +
> +build() {
> +    make devmode -j"$(nproc)"
>
> Yes, otherwise it won't compile
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/pacstall/pacstall-programs/pull/1439#discussion_r937206584), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AOAFN4ZJU2BVYBMQP6HLSXDVXL3X5ANCNFSM5455Y6GQ).
> You are receiving this because you commented.Message ID: ***@***.***>

2022-08-03 23:23 UTC, WRM-42 commented
It uses the latest git commit

2022-08-03 23:46 UTC, Henryws commented
Yes I know, I meant what does devmode do? Does it produce a dev binary, or a release binary?

2022-08-03 23:48 UTC, Henryws commented
Because it appears that you can replace `devmode` with `release`.

2022-08-03 23:52 UTC, Henryws requested changes

2022-08-03 23:52 UTC, Henryws commented on packages/monero-gui-git/monero-gui-git.pacscript
> +    make devmode -j"$(nproc)"
```suggestion
    make release -j"$(nproc)"
```

2022-08-04 00:20 UTC, WRM-42 commented
> Yes I know, I meant what does devmode do? Does it produce a dev binary, or a release binary?

It produces a dev binary: https://github.com/monero-project/monero#on-linux-and-macos

2022-08-04 00:33 UTC, Henryws commented
Ok then replace `devmode` with `release`.

2022-08-04 15:17 UTC, WRM-42 commented
Doesn't work

![cmake](https://user-images.githubusercontent.com/83829346/182883977-c505301f-618d-4450-9d85-a04fa0db388e.png)

2022-08-04 16:09 UTC, Henryws commented
Then update the submodules as it instructs.

2022-08-06 13:40 UTC, Henryws commented
CI fails again

2022-08-28 20:27 UTC, cat-master21 commented
`make install` needs to be replaced by `make release` https://github.com/monero-project/monero-gui#building-on-linux

2022-10-25 04:11 UTC, closed without merging