add: `an-anime-game-launcher-gtk-bin`
pacstall/pacstall-programs pull request #1479
Opened 2022-08-12 21:20 UTC by Mar0xy

2022-08-12 21:43 UTC, Henryws requested changes

2022-08-12 21:43 UTC, Henryws commented on packages/an-anime-game-launcher-gtk-bin/an-anime-game-launcher-gtk-bin.pacscript
> +version=1.0.0
Quote these.

2022-08-12 21:49 UTC, Mar0xy commented on packages/an-anime-game-launcher-gtk-bin/an-anime-game-launcher-gtk-bin.pacscript
> +version=1.0.0
Done

2022-08-14 17:22 UTC, Henryws requested changes

2022-08-14 17:22 UTC, Henryws commented on packages/an-anime-game-launcher-gtk-bin/an-anime-game-launcher-gtk-bin.pacscript
> +    sudo chmod +x "${SRCDIR}/an-anime-game-launcher"
```suggestion
    sudo chmod +x "anime-game-launcher"
```

2022-08-14 17:22 UTC, Henryws commented on packages/an-anime-game-launcher-gtk-bin/an-anime-game-launcher-gtk-bin.pacscript
> +    sudo cp an-anime-game-launcher "${STOWDIR}/${name}/usr/lib/${pkgname}/"
```suggestion
    sudo cp anime-game-launcher "${STOWDIR}/${name}/usr/lib/${pkgname}/"
```

2022-08-14 17:22 UTC, Henryws commented on packages/an-anime-game-launcher-gtk-bin/an-anime-game-launcher-gtk-bin.pacscript
> +    sudo ln -s -r "${STOWDIR}/${name}/usr/lib/${pkgname}/an-anime-game-launcher" "${STOWDIR}/${name}/usr/bin/an-anime-game-launcher"
```suggestion
    sudo ln -s -r "${STOWDIR}/${name}/usr/lib/${pkgname}/anime-game-launcher" "${STOWDIR}/${name}/usr/bin/an-anime-game-launcher"
```

2022-08-14 18:21 UTC, Henryws approved these changes

2022-08-14 18:21 UTC, merged