add: komorebi-fork-deb
pacstall/pacstall-programs pull request #1509
Opened 2022-08-26 08:23 UTC by 0x262D

2022-08-26 10:15 UTC, Mar0xy commented
Missing addition to packagelist.
Please add the package name in the packagelist file in the correct alphabetical spot.

2022-08-27 19:10 UTC, 0x262D commented
@Mar0xy check pls

2022-08-27 19:14 UTC, Henryws requested changes

2022-08-27 19:14 UTC, Henryws commented on packages/komorebi-fork-deb/komorebi-fork-deb.pacscript
> +
This line isn't needed.

2022-08-27 19:27 UTC, 0x262D commented on packages/komorebi-fork-deb/komorebi-fork-deb.pacscript
> +
removed

2022-08-27 19:32 UTC, Henryws approved these changes

2022-08-27 19:32 UTC, merged