feat(emacs)!: update script to latest spec
pacstall/pacstall-programs pull request #1547
Opened 2022-09-05 10:00 UTC by wizard-28

Updates the pacscript to the latest PKGBUILD spec
https://aur.archlinux.org/cgit/aur.git/commit/?h=emacs-git&id=b9eb3b405717f8df37b38217dbb7d361b8ffca08

Closes #1303

2022-09-05 10:01 UTC, wizard-28 commented
@JonBoyleCoding Please test if this works.

2022-09-05 10:04 UTC, wizard-28 commented
Also @Henryws this is a breaking change for the pacscript as a lot of deprecated features have been removed from it

2022-09-25 09:35 UTC, wizard-28 commented
@Henryws The CI doesn't work, jitterbit fails.

2022-10-14 03:04 UTC, Henryws requested changes
![image](https://user-images.githubusercontent.com/58742515/195752916-0a62a471-a403-4bf8-a29e-b749f7f10164.png)

2022-10-14 08:22 UTC, JonBoyleCoding commented
Sorry I haven't had the time to test this out. I won't have time until end of next week to do anything on the side - if you still need some help with this by then I can have a look then.

2022-10-30 17:06 UTC, JonBoyleCoding reviewed
I am testing for Ubuntu 20.04 as that is what I am limited to by my organisation for the time being. If you wish to support that still, then the following packages will need to be used instead of the ones currently in the package.

If changed, the pacscript seems to install fine on 20.04. I would propose the change myself for multiple distros, but I don't know if you wish to go down that path or what the best practice would be.

2022-10-30 17:06 UTC, JonBoyleCoding commented on packages/emacs/emacs.pacscript
> +    depends+=" libgccjit0 libgccjit-11-dev"
For Ubuntu 20.04 - needs to be libgccjit-10-dev as 11+ isn't in the repository

2022-10-30 17:06 UTC, JonBoyleCoding commented on packages/emacs/emacs.pacscript
> +  depends+=" libjpeg-turbo8 libpng16-16 libgif-dev libwebp7 libtiff5 libxpm-dev"
libwebp7 needs to be libwebp6 for Ubuntu 20.04

2022-11-28 23:32 UTC, Henryws commented
@wizard-28 can you look at the reviews?

2022-12-27 14:33 UTC, wizard-28 commented
For Ubuntu:

```
emacs : Depends: libgtk-3-dev but it is not going to be installed
         Depends: libwebp6 but it is not installable
```

For Debian:

```
 emacs : Depends: libjpeg-turbo8 but it is not installable
         Depends: libwebp6 but it is not installable
```

2022-12-27 14:37 UTC, wizard-28 commented
`libwebp7` seems to be present in `ubuntu:latest`, but not `libwebp6`

`libgtk-3-dev` is present in `ubuntu:latest`, but not in `ubuntu:devel` and `ubuntu:rolling`

2022-12-27 14:37 UTC, wizard-28 commented
@Henryws what to do?

2022-12-27 14:38 UTC, Henryws commented
Maybe use incompatible

2022-12-27 14:43 UTC, wizard-28 commented
> Maybe use incompatible

Should I add OS-specific dependencies?

2022-12-27 14:43 UTC, Henryws commented
Sure

2022-12-27 15:42 UTC, Henryws approved these changes

2022-12-27 15:42 UTC, merged