refactor(ardour-git): move symlinks to `postinst`
pacstall/pacstall-programs pull request #1611
Opened 2022-10-05 14:04 UTC by echometerain

2022-10-08 14:51 UTC, Henryws requested changes
You can't use `$STOWDIR` in `postinst` and `removescript`. Once you are in those functions, you are not dealing with symlinks.

Example:
```bash
sudo ln -sf "$STOWDIR/$name/opt/bla" "$STOWDIR/$name/usr/bin/bla"

# should be

sudo ln -sf "/opt/bla" "/usr/bin/bla"
```

2022-10-17 19:28 UTC, Henryws requested changes

2022-10-17 19:28 UTC, Henryws commented on packages/ardour-git/ardour-git.pacscript
> +provides="ladspa-host lv2-host vst-host vst3-host ardour ardour-data"
Make this an array

2022-10-19 18:58 UTC, Henryws commented
Add python as a build dependency

2022-10-20 19:07 UTC, Henryws commented
Still fails.

2022-10-21 19:29 UTC, Henryws commented
I’m gonna test manually when I get home.

2022-10-21 21:07 UTC, Henryws commented
Ok turns out the CI was installing the repo one... New issue now.

2022-10-22 04:04 UTC, cat-master21 requested changes
yes this may add a extra dependency but it solves the issue of being able to work on multiple systems. I wish I could do it if the package provides it but I don't know if pacstall supports it.

2022-10-26 01:03 UTC, Henryws commented
Try adding [libasound2](https://packages.debian.org/libasound2) to the build deps list.

2022-10-26 16:56 UTC, Henryws commented
Why can’t debian detect the alsa package?

2022-11-23 22:36 UTC, Henryws approved these changes

2022-11-23 22:36 UTC, merged