fix(kalendar-git): fix build with pacstall 3 and Ubuntu 22.10
pacstall/pacstall-programs pull request #1689
Opened 2022-10-23 07:21 UTC by Zahrun

Compiles fine in Kubuntu 22.10 (will not work in versions < 22.10 nor debian)

2022-10-23 12:47 UTC, Henryws requested changes

2022-10-23 12:47 UTC, Henryws commented on packages/kalendar-git/kalendar-git.pacscript
> +  cd "${STOWDIR}/${name}/usr/lib/x86_64-linux-gnu/" || exit
```suggestion
  cd "${STOWDIR}/${name}/usr/lib/x86_64-linux-gnu/"
```

2022-10-23 12:47 UTC, Henryws commented on packages/kalendar-git/kalendar-git.pacscript
> +  cd build || exit
```suggestion
  cd build
```

2022-10-23 22:55 UTC, Henryws commented
CI fails

2022-10-24 11:08 UTC, Zahrun commented
> CI fails

CI does not run in Ubuntu 22.10
```
See also "/tmp/pacstall/kalendar/build/CMakeFiles/CMakeOutput.log".
  with requested version "5.96.0".

  The following configuration files were considered but not accepted:

    /usr/share/ECM/cmake/ECMConfig.cmake, version: 5.92.0
```
However, https://packages.ubuntu.com/kinetic/extra-cmake-modules

2022-10-24 12:58 UTC, Henryws approved these changes

2022-10-24 12:58 UTC, merged