add: `protonup-qt-git`
pacstall/pacstall-programs pull request #1782
Opened 2022-11-24 22:53 UTC by DavidoTek

Adds a ProtonUp-Qt `pascript`. It will fetch and download the latest tag release from GitHub.
Issue for ProtonUp-Qt: https://github.com/DavidoTek/ProtonUp-Qt/issues/83

## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [X] Contact devs (me @DavidoTek)
- [ ] Add maintainer to pacscript

2022-11-24 23:06 UTC, Henryws requested changes

2022-11-24 23:06 UTC, Henryws commented on packages/protonup-qt-git/protonup-qt-git.pacscript
> +
```suggestion
```

2022-11-24 23:32 UTC, Henryws requested changes

2022-11-24 23:32 UTC, Henryws commented on packages/protonup-qt-git/protonup-qt-git.pacscript
> +
```suggestion
```

2022-11-24 23:32 UTC, Henryws commented on packages/protonup-qt-git/protonup-qt-git.pacscript
> +
```suggestion
```

2022-11-24 23:32 UTC, Henryws commented on packages/protonup-qt-git/protonup-qt-git.pacscript
> +    sudo ln -s "${STOWDIR}/${name}/usr/bin/net.davidotek.pupgui2.sh" "/usr/bin/protonup-qt"
This won't work. You probably want `sudo ln -s /usr/bin/net.davidotek.pupgui2.sh /usr/bin/protonup-qt` in `postinst`

2022-11-25 18:08 UTC, Henryws commented
CI fails.

2022-11-25 22:15 UTC, DavidoTek commented
I see. Is it possible to install Python dependencies using `pip`? PySide6 isn't available in the Ubuntu repos.

```
Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
ERROR: Could not find a version that satisfies the requirement PySide6-Essentials>=6.3.0 (from versions: none)
ERROR: No matching distribution found for PySide6-Essentials>=6.3.0
[!] ERROR: Could not prepare protonup-qt-git properly
```

2022-11-26 02:29 UTC, Henryws commented
Sure.

2022-11-28 23:31 UTC, Henryws commented
@DavidoTek any updates on this?

2022-11-29 10:12 UTC, DavidoTek commented
I did some investigation. Seems like `PySide6-Essentials` isn't available for the used Python version. `PySide6` should work fine.

2022-12-05 09:36 UTC, DavidoTek commented
Hmm, not sure what's causing the issue.
Do you have any idea what the problem is? Maybe I am missing something obvious?

2022-12-15 17:06 UTC, sonic2kk commented
> Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
> ERROR: Could not find a version that satisfies the requirement PySide6 (from versions: none)
> ERROR: No matching distribution found for PySide6

These errors usually come from a compatible package version not being found for the current Python version (in this case, Python 3.10). But there should be a `pyside6` package available (afaik Pip packages are case-insensitive so casing shouldn't matter). The supported versions noted on the [PyPI](https://pypi.org/project/PySide6/) page should work with Python 3.10 I believe too: `Python <3.12, >=3.7`.

I'm not sure if this could be causing issues, but the PyPI page also notes:

> Please note: this wheel is an alias to other two wheels [PySide6_Essentials](https://pypi.org/project/PySide6_Essentials) and [PySide6_Addons](https://pypi.org/project/PySide6_Addons), which contains a predefined list of Qt Modules.

2022-12-15 20:42 UTC, DavidoTek commented
> These errors usually come from a compatible package version not being found for the current Python version 

That's what I though first too, there was a similar issue with the AppImage (that's why it's still using PySide 6.2).
But I don't see a reason why this should occur here, the Python version is new enough.

> Please note: this wheel is an alias to other two wheels [PySide6_Essentials](https://pypi.org/project/PySide6_Essentials) and [PySide6_Addons](https://pypi.org/project/PySide6_Addons)

Problem occurs with both `PySide6` and `PySide6-Essentials` (versions gets removed from the requirements.txt before installing).

2023-01-01 03:34 UTC, Henryws commented
@DavidoTek Any updates?

2023-01-01 17:50 UTC, DavidoTek commented
> @DavidoTek Any updates?

I've no clue why it is not working. For some reason, installing PySide6 using pip doesn't work. I'm also not sure if it is a good idea to install/remove global Python dependencies as it is not that simple to detect them, so maybe a different approach would be better:

**Alternatively**, I could create a different new *pacscript* that downloads and installs the [AppImage](https://github.com/DavidoTek/ProtonUp-Qt/releases) instead. Like the AUR package [protonup-qt-bin](https://aur.archlinux.org/packages/protonup-qt-bin).
That would also eliminate the problem with the global dependencies as all dependencies are included inside the AppImage.
The AppImage is ~58MB in size. Would it be okay to do it this way @Henryws ?

2023-01-01 18:11 UTC, wizard-28 commented
> > @DavidoTek Any updates?
> 
> I've no clue why it is not working. For some reason, installing PySide6 using pip doesn't work. I'm also not sure if it is a good idea to install/remove global Python dependencies as it is not that simple to detect them, so maybe a different approach would be better:
> 
> **Alternatively**, I could create a different new _pacscript_ that downloads and installs the [AppImage](https://github.com/DavidoTek/ProtonUp-Qt/releases) instead. Like the AUR package [protonup-qt-bin](https://aur.archlinux.org/packages/protonup-qt-bin). That would also eliminate the problem with the global dependencies as all dependencies are included inside the AppImage. The AppImage is ~58MB in size. Would it be okay to do it this way @Henryws ?

Yeah making an AppImage pacscript is fine, name it `protonup-qt-app` as per our convention. Leave this PR open for now and make a new PR.

2023-01-06 23:40 UTC, Henryws commented
`protonup-qt-app` was added so closing.

2023-01-06 23:40 UTC, closed without merging