add: `gir1.2-xapp-1.0-deb`
pacstall/pacstall-programs pull request #1834
Opened 2022-12-12 15:41 UTC by Zahrun

2022-12-12 16:01 UTC, Zahrun commented
Requires https://github.com/pacstall/pacstall-programs/pull/1833

2022-12-16 17:33 UTC, Henryws requested changes

2022-12-16 17:33 UTC, Henryws commented on packages/gir1.2-xapp-1.0-deb/gir1.2-xapp-1.0-deb.pacscript
> +pacdeps=("libxapp1")
```suggestion
pacdeps=("libxapp1-deb")
```

2022-12-16 17:40 UTC, Henryws approved these changes

2022-12-16 17:40 UTC, merged