add: `xapps-common-deb`
pacstall/pacstall-programs pull request #1836
Opened 2022-12-12 15:56 UTC by Zahrun

2022-12-13 03:15 UTC, Henryws requested changes

2022-12-13 03:15 UTC, Henryws commented on packages/xapps-common-deb/xapps-common-deb.pacscript
> +description="Xapp provides components which are common to multiple desktop environments and required to implement cross-DE solutions"
No package name in description.

2022-12-13 09:56 UTC, Zahrun commented on packages/xapps-common-deb/xapps-common-deb.pacscript
> +description="Xapp provides components which are common to multiple desktop environments and required to implement cross-DE solutions"
Ok

2022-12-16 16:39 UTC, Henryws requested changes
Add `hash`.

2022-12-16 16:48 UTC, Henryws requested changes
Add `repology` array.

2022-12-16 17:03 UTC, Zahrun commented
Ok

2022-12-16 17:15 UTC, Henryws approved these changes

2022-12-16 17:15 UTC, merged