add: topgrade-musl-bin
pacstall/pacstall-programs pull request #1840
Opened 2022-12-15 13:37 UTC by derphilipp

topgrade-musl-bin added, as the latest gnu variant broke is now broken on currently stable debian
As a user you then have the choice to use topgrade-bin or topgrade-musl-bin

2022-12-15 14:09 UTC, wizard-28 requested changes

2022-12-15 14:09 UTC, wizard-28 commented on packages/topgrade-musl-bin/topgrade-musl-bin.pacscript
> +maintainer="charitarthchugh <37895518+charitarthchugh@users.noreply.github.com>"
@charitarthchugh, are you willing to maintain this pacscript?

2022-12-15 14:39 UTC, charitarthchugh commented
Unfortunately, I cannot

2022-12-15 14:41 UTC, wizard-28 commented on packages/topgrade-musl-bin/topgrade-musl-bin.pacscript
> +maintainer="charitarthchugh <37895518+charitarthchugh@users.noreply.github.com>"
@derphilipp Are you willing to maintain this pacscript?

2022-12-15 15:34 UTC, derphilipp commented
Unfortunately not;

2022-12-15 17:26 UTC, Henryws requested changes

2022-12-15 17:26 UTC, Henryws commented on packages/topgrade-musl-bin/topgrade-musl-bin.pacscript
> +}
```suggestion
```

2022-12-16 13:14 UTC, Henryws approved these changes
Works.

2022-12-16 13:14 UTC, merged