add: `wezterm-app`
pacstall/pacstall-programs pull request #1845
Opened 2022-12-19 17:09 UTC by smokeythemonkey

## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [ ] Contact devs
- [x] Add maintainer to pacscript

2022-12-19 17:14 UTC, Henryws commented
Uh, fix `packagelist`

2022-12-19 17:16 UTC, smokeythemonkey commented
Whoops :D. Done :+1:

2022-12-19 17:21 UTC, Henryws commented
Fix the `packagelist` so the *only* thing being added is `wezterm-app`, instead of moving around other stuff.

2022-12-19 19:30 UTC, Henryws requested changes

2022-12-19 19:30 UTC, Henryws commented on packages/wezterm-app/wezterm-app.pacscript
> +hash=""
Why is this empty?

2022-12-19 19:30 UTC, Henryws commented on packages/wezterm-app/wezterm-app.pacscript
> +description="WezTerm is a GPU-accelerated cross-platform terminal emulator and multiplexer written by @wez and implemented in Rust"
Don't use the name of the package in the description.

2022-12-19 19:30 UTC, Henryws commented on packages/wezterm-app/wezterm-app.pacscript
> +
```suggestion
```

2022-12-19 22:11 UTC, smokeythemonkey commented on packages/wezterm-app/wezterm-app.pacscript
> +hash=""
honestly just forgot

2022-12-19 22:19 UTC, Henryws commented on packages/wezterm-app/wezterm-app.pacscript
> +pkgname="wezterm"
```suggestion
gives="wezterm"
```

2022-12-20 13:35 UTC, wizard-28 approved these changes

2022-12-20 19:48 UTC, Henryws requested changes

2022-12-20 19:48 UTC, Henryws commented on packages/wezterm-app/wezterm-app.pacscript
> +  #wget -q "https://raw.githubusercontent.com/pacstall/pacstall-programs/master/packages/${name}/${pkgname}.desktop"
Uncomment these

2022-12-20 20:06 UTC, Henryws approved these changes

2022-12-20 20:07 UTC, merged