Update discord-canary.pacscript
pacstall/pacstall-programs pull request #30
Opened 2021-06-10 22:57 UTC by aranym0

2021-06-10 23:00 UTC, aranym0 commented
Seems there's something up with the hash.
I suspect it is related to me using Get-FileHash in powershell to obtain it, so all of the letters are uppercase- so it technically won't match the output of sha256sum.

I'll update that real quick here.

2021-06-10 23:04 UTC, aranym0 commented
Fixed.

2021-06-11 04:27 UTC, wizard-28 requested changes

2021-06-11 04:27 UTC, wizard-28 commented on packages/discord-canary/discord-canary.pacscript
>  build_depends=""
```suggestion
 
```
Everything is good, but can you remove this empty variable?

2021-06-11 09:21 UTC, aranym0 commented
done

2021-06-11 09:23 UTC, wizard-28 requested changes

2021-06-11 09:23 UTC, wizard-28 commented on packages/discord-canary/discord-canary.pacscript
>  gives="discord-canary"
```suggestion

```
Its not used in pacstall

2021-06-11 09:27 UTC, aranym0 commented
done

2021-06-11 09:28 UTC, wizard-28 requested changes

2021-06-11 09:28 UTC, wizard-28 commented on packages/discord-canary/discord-canary.pacscript
> +
```suggestion

```
Empty line xD

2021-06-11 09:31 UTC, wizard-28 approved these changes
Approved!

2021-06-11 09:32 UTC, merged