add cantata-deb
pacstall/pacstall-programs pull request #304
Opened 2021-09-19 02:16 UTC by ty1118

2021-09-19 02:52 UTC, wizard-28 requested changes

2021-09-19 02:52 UTC, wizard-28 commented on packages/cantata-deb/cantata-deb.pacscript
> +url="https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/cantata-qt/+files/cantata_2.4.2-0build1~ubuntu20.10_amd64.deb"
Why is this pointing to `20.10`'s `.deb`. It won't work correctly in other versions of Ubuntu... I thought you would make a `nosuffix` ( no suffix at the end, builds the package first then installs ) package with the instructions given [here](https://github.com/CDrummond/cantata/blob/master/INSTALL).

See, if you don't want to make one yourself anymore you can always say so. Someone can volunteer to make one then.

And if your thinking making this `-deb` script was a waste of time. Then no, it wasn't it'll help the future volunteer (or you yourself! ) to make the correct script, as most of the tedious work like finding the dependencies etc is already done here.

2021-09-19 15:08 UTC, closed without merging

2021-09-19 15:10 UTC, Henryws commented
This PR was closed because:

1) your extracting the deb from a PPA. At that point, why not just use the PPA
2) You are using a version specific Deb file, so this will not work on newer versions of Ubuntu

2021-09-20 17:38 UTC, ty1118 commented
Please do. I'm still learning. Baby steps are indeed needed.