add cantata package
pacstall/pacstall-programs pull request #321
Opened 2021-09-25 10:06 UTC by ty1118

2021-09-25 10:47 UTC, wizard-28 requested changes

2021-09-25 10:47 UTC, wizard-28 commented on packages/canata/cantata.pacscript
> +# vim:set ft=sh ts=4 sw=4 et:
```suggestion
name="cantata"
pkgname="cantata"
version="2.4.2"
url="https://github.com/CDrummond/cantata/releases/download/v$version/cantata-$version.tar.bz2"
depends="mpd media-player-info fonts-font-awesome libcddb2 qttools5-dev qtbase5-dev qtchooser qtmultimedia5-dev qt5-qmake qtbase5-dev-tools libqt5svg5 libebur128-1 libmusicbrainz5cc2v5 libqt5multimedia5"
description="Cantata is a graphical client for MPD. It is support for Linux, MacOSX, and Windows, Multiple MPD collections and it has a Highly customizable layout."
maintainer="ty1118 <tylerbj16@gmail.com>"
hash="3ed25d0c838720af7ed08b89a30f3e05d6952d40a5f520f29b3558b2eacdec82"

prepare() {
    mkdir build
    cd build
}

build() {
    cmake -DCMAKE_BUILD_TYPE=Release ..
    make -j$(nproc)
}

install() {
    sudo make install DESTDIR=${STOWDIR}/${name}
}

# vim:set ft=sh ts=4 sw=4 et:
```

Fixed weird `\r` chars, and extra space in `depends`, suggested to change the whole file for surety.

2021-09-25 10:59 UTC, wizard-28 approved these changes

2021-09-25 10:59 UTC, merged

2021-09-27 21:34 UTC, Henryws commented
Can you fix it with another pr?

2021-09-28 04:25 UTC, wizard-28 commented
> @ty1118 There is a typo in the folder name

I fixed it in #332