add: `clipboard-bin`
pacstall/pacstall-programs pull request #3241
Opened 2023-05-05 10:08 UTC by wizard-28

2023-05-05 14:21 UTC, Henryws requested changes

2023-05-05 14:21 UTC, Henryws commented on packages/clipboard-bin/clipboard-bin.pacscript
> +		sudo install -Dm 755 "lib/libcbwayland.so" "${pkgdir}/usr/lib/libcbwayland.so"
Run shfmt.

2023-05-06 02:15 UTC, Henryws requested changes

2023-05-06 02:15 UTC, Henryws commented on packages/clipboard-bin/clipboard-bin.pacscript
> +description="Cut, copy, and paste anything in your terminal."
```suggestion
description="Cut, copy, and paste anything in your terminal"
```

2023-05-06 02:20 UTC, Henryws approved these changes

2023-05-06 02:20 UTC, merged

2023-05-17 21:53 UTC, Slackadays commented
@wizard-28 needs to be updated to 0.7.1