add: `kiri`
pacstall/pacstall-programs pull request #3247
Opened 2023-05-05 13:43 UTC by MarcelRobitaille

## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [ ] Contact devs
- [ ] Add maintainer to pacscript

2023-05-05 16:02 UTC, Henryws requested changes

2023-05-05 16:02 UTC, Henryws commented on packages/kiri-git/kiri-git.pacscript
> +build_depends=("git" "python3-pip")
```suggestion
build_depends=("git" "python3-pip" "pkg-config")
```

2023-05-05 16:07 UTC, MarcelRobitaille commented on packages/kiri-git/kiri-git.pacscript
> +depends=("git" "build-essential" "libgtk-3-dev" "pkg-config" "opam" "python-is-python3" "python3-pip" "kicad" "dos2unix" "coreutils" "zenity" "librsvg2-bin" "imagemagick" "xdotool" "rename")
The dependencies are taken directly from upstream.

- This software works with git, so it's a runtime dependency as well as a build dependency
- I agree that `build-essential` is odd. It's taken from upstream
- `pkg-config` is again taken from upstream. It's not required to build. I don't use it in the pacscript. I'm not sure if it's really needed upstream though.

2023-05-05 16:30 UTC, Henryws commented on packages/kiri-git/kiri-git.pacscript
> +depends=("git" "build-essential" "libgtk-3-dev" "pkg-config" "opam" "python-is-python3" "python3-pip" "kicad" "dos2unix" "coreutils" "zenity" "librsvg2-bin" "imagemagick" "xdotool" "rename")
`git` is already installed with pacstall, same with `build-essential`, and my bad, `pkg-config` should stay in `build_depends`

2023-05-08 12:58 UTC, MarcelRobitaille commented on packages/kiri-git/kiri-git.pacscript
> +depends=("git" "build-essential" "libgtk-3-dev" "pkg-config" "opam" "python-is-python3" "python3-pip" "kicad" "dos2unix" "coreutils" "zenity" "librsvg2-bin" "imagemagick" "xdotool" "rename")
@Henryws Maybe there was a miscommunication. My build script doesn't depend on `pkg-config`. It's listed as a dependency upstream.

2023-06-15 02:35 UTC, Henryws commented on packages/kiri-git/kiri-git.pacscript
> +build_depends=("git" "python3-pip")
This still needs to happen I believe.

2023-06-15 16:15 UTC, Henryws requested changes

2023-06-15 16:15 UTC, Henryws commented on packages/kiri-git/kiri-git.pacscript
> +version=$(pkgver)
```suggestion
version="$(pkgver)"
```

2023-06-15 16:15 UTC, Henryws commented on packages/kiri-git/kiri-git.pacscript
> +
```suggestion
```

2023-06-15 16:15 UTC, Henryws commented on packages/kiri-git/kiri-git.pacscript
> +arch=("any")
```suggestion
```

2023-06-15 16:15 UTC, Henryws commented on packages/kiri-git/kiri-git.pacscript
> +    sudo ln -s "../../opt/kiri/bin/${bin}" "${pkgdir}/usr/bin/${bin}"
You can't use `ln` inside `install()`.[^1]

[^1]: https://github.com/pacstall/pacstall/wiki/Common-Pacscript-practices#handling-symlinks

2023-09-27 11:49 UTC, Elsie19 commented
Stale.

2023-09-27 11:49 UTC, closed without merging