fix(wine-staging-git): remove missing dependencies
pacstall/pacstall-programs pull request #3370
Opened 2023-05-10 23:38 UTC by echometerain

2023-05-11 00:33 UTC, echometerain commented
last commit removes libgstreamer-plugins-base1.0-dev:i386

2023-05-11 00:36 UTC, echometerain commented
turns out there was a duplicate

2023-05-11 12:47 UTC, Henryws requested changes

2023-05-11 12:47 UTC, Henryws commented on packages/wine-staging-git/wine-staging-git.pacscript
>    ln -s "../conf.avail/30-win32-aliases.conf" "${pkgdir}/usr/share/fontconfig/conf.default/30-win32-aliases.conf"
You can't symlink files in `install`

2023-05-11 23:12 UTC, Henryws requested changes

2023-05-11 23:12 UTC, Henryws commented on packages/wine-staging-git/wine-staging-git.pacscript
> +  sudo ln -s "../conf.avail/30-win32-aliases.conf" "${pkgdir}/usr/share/fontconfig/conf.default/30-win32-aliases.conf"
postinst is run from `/` so `../` can't exist. Figure out where this file actually installs to

2023-05-22 14:27 UTC, Henryws commented
Any updates on this PR?

2023-05-24 00:40 UTC, Henryws commented
Please don't update the branch if you don't need to.

2023-05-27 15:54 UTC, echometerain commented
> Any updates on this PR?

sorry I was busy for the last couple of days

2023-05-28 00:59 UTC, echometerain commented
holy moly I think it worked

2023-05-28 07:14 UTC, Henryws approved these changes

2023-05-28 07:14 UTC, merged