upd: `obs-backgroundremoval-git`
pacstall/pacstall-programs pull request #4160
Opened 2023-07-29 05:33 UTC by Zahrun

2023-07-29 12:37 UTC, Elsie19 requested changes

2023-07-29 12:37 UTC, Elsie19 commented on packages/obs-backgroundremoval-git/obs-backgroundremoval-git.pacscript
> +}
Why are we cloning curl?

2023-07-29 12:37 UTC, Elsie19 requested changes
Fix title

2023-07-30 07:54 UTC, Zahrun commented on packages/obs-backgroundremoval-git/obs-backgroundremoval-git.pacscript
> +}
Not needed

2023-07-30 07:55 UTC, Zahrun commented
> Fix title

As in it's a fix?

2023-07-30 15:33 UTC, Elsie19 commented
> > Fix title
> 
> As in it's a fix?

add the fix description: <kbd>fix(obs-backgroundremoval-git): description</kbd>

2023-07-30 21:40 UTC, Elsie19 commented
> mv: cannot move '/usr/src/pacstall/obs-backgroundremoval-git/usr/lib/x86_64-linux-gnu' to a subdirectory of itself, '/usr/src/pacstall/obs-backgroundremoval-git/usr/lib/x86_64-linux-gnu/x86_64-linux-gnu'

2023-08-02 21:06 UTC, Elsie19 requested changes

2023-08-02 21:06 UTC, Elsie19 commented on packages/obs-backgroundremoval-git/obs-backgroundremoval-git.pacscript
> +  mkdir build_x86_64 && cd build_x86_64 || exit
```suggestion
  mkdir build_x86_64 && cd build_x86_64 || return 1
```

2023-08-02 21:06 UTC, Elsie19 commented on packages/obs-backgroundremoval-git/obs-backgroundremoval-git.pacscript
> +  cd build_x86_64 || exit
```suggestion
  cd build_x86_64 || return 1
```

2023-08-02 21:24 UTC, Elsie19 requested changes

2023-08-02 21:24 UTC, Elsie19 commented on packages/obs-backgroundremoval-git/obs-backgroundremoval-git.pacscript
> +  cmake --build . -j"$(nproc)" > /dev/null
```suggestion
  cmake --build . -j"${NCPU}" > /dev/null
```

2023-08-02 21:35 UTC, Elsie19 approved these changes

2023-08-02 21:36 UTC, merged