add: `xone-git`
pacstall/pacstall-programs pull request #4222
Opened 2023-08-15 11:52 UTC by FelisDiligens

## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [ ] Contact devs
- [ ] Add maintainer to pacscript

## Description

[xone](https://github.com/medusalix/xone) is a Linux kernel driver (dkms) for Xbox One and Xbox Series X|S accessories. It makes it possible to use the official [Xbox wireless adapter](https://www.xbox.com/en-US/accessories/adapters/wireless-adapter-windows).

I tried to mostly replicate the behavior of the installation/uninstallation scripts from the original project, see:
- [xone/install.sh](https://github.com/medusalix/xone/blob/master/install.sh)
- [xone/uninstall.sh](https://github.com/medusalix/xone/blob/master/uninstall.sh)
- [xone/install/firmware.sh](https://github.com/medusalix/xone/blob/master/install/firmware.sh)

See also:
- [AUR: xone-dkms-git](https://aur.archlinux.org/packages/xone-dkms-git)
- [AUR: xone-dongle-firmware](https://aur.archlinux.org/packages/xone-dongle-firmware)

I tested it locally on my Ubuntu 23.04 installation. (`pacstall -I` and `-R`)

First commit here, I hope I'm doing this right. ^^

2023-08-15 12:14 UTC, Elsie19 requested changes

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +makedepends=('git' 'curl' 'cabextract')
```suggestion
makedepends=('cabextract')
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +
```suggestion
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +}
```suggestion
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +  echo "* Preparing module..."
```suggestion
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +  echo "* Copying module into /usr/src..."
```suggestion
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +  echo "* Blacklisting xpad module..."
```suggestion
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +
```suggestion
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +    echo "* Checksum did not match!"
```suggestion
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +    exit 1
```suggestion
    return 1
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +  echo "* Getting xone version"
```suggestion
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +  echo "* Running 'dkms install'"
```suggestion
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +  echo "* Unloading conflicting kernel modules"
```suggestion
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +    echo "* Unloading modules: ${modules}"
```suggestion
```

2023-08-15 12:14 UTC, Elsie19 commented on packages/xone-git/xone-git.pacscript
> +  echo "* Deleting xone dkms files"
```suggestion
```

2023-08-15 12:45 UTC, FelisDiligens commented
Hi, it seems like the tests are failing, because it doesn't install the right kernel headers (`linux-headers-generic`)...
```txt
Error! Your kernel headers for kernel 5.15.0-1042-azure cannot be found.

Please install the linux-headers-5.15.0-1042-azure package or use the --kernelsourcedir option to tell DKMS where it's located.

dpkg: error processing package xone-git (--configure):
 installed xone-git package post-installation script subprocess returned error exit status 1
```
Should I add `"linux-headers-$(uname -r)"` to `depends` or `optdepends`?

2023-08-17 22:06 UTC, FelisDiligens commented
Sadly, the kernel headers for Azure aren't in most apt repositories:
```
 [*] WARNING: linux-headers-5.15.0-1042-azure does not exist in apt repositories
```
So the pacscript still fails to install in 10 out of 12 test cases. dkms stops dead in it's tracks.

I presume, this is because the tests run on Azure with custom Linux kernels instead of the `generic` (ubuntu) or `common` (debian) ones that come with a normal installation of these distros...

Sorry for the mess.
I'm not entirely sure what to do about it. :/
What do you think?

2023-08-19 15:14 UTC, Elsie19 commented
Again, I've never dealt with kernel module pacscripts, so your guess is as good as mine.

2023-08-19 19:21 UTC, closed without merging

2023-08-19 19:21 UTC, FelisDiligens commented
Hmm, ok. Well, since it doesn't seem to be possible to pass the tests (see also: [community/discussions/28607](https://github.com/orgs/community/discussions/28607)), I'll close this PR now.  
Thank you for your time! <3