Update libresprite version
pacstall/pacstall-programs pull request #449
Opened 2021-10-27 02:02 UTC by echometerain

2021-10-30 17:47 UTC, wizard-28 requested changes

2021-10-30 17:47 UTC, wizard-28 commented on packages/libresprite-git/libresprite-git.pacscript
> +	printf "Icon=/usr/share/pixmaps/libresprite.png" | sudo tee -a "$STOWDIR/$name/usr/share/applications/libresprite.desktop"
```suggestion
	printf "Icon=libresprite" | sudo tee -a "$STOWDIR/$name/usr/share/applications/libresprite.desktop"
```

It should be just `libresprite` if it's in `pixmaps`, test it once before commiting though

2021-10-30 20:24 UTC, echometerain commented
The icons and .desktop installs are redundant. Ninja installs them automatically

2021-11-01 05:42 UTC, wizard-28 approved these changes

2021-11-03 17:45 UTC, merged