upd(obs-backgroundremoval): 1.1.3 -> 1.1.6
pacstall/pacstall-programs pull request #4576
Opened 2023-09-22 11:33 UTC by umireon

2023-09-22 12:39 UTC, umireon commented
All the systems are included in the incompatible field. I didn't change the incompatible field and I don't know why every system is incompatible.

2023-09-25 20:25 UTC, Elsie19 commented
Have you tested on supposed incompatible systems?

2023-09-25 21:10 UTC, umireon commented
I think we need to add PPA OBS distribution to pacstall repository first.

2023-09-26 05:49 UTC, Zahrun commented
> I think we need to add PPA OBS distribution to pacstall repository first.

I met some build dependencies missing in the distros which are in the incompatible field.
One option is to add the ppa to the pacscript, but I preferred to avoid that, so I just excluded the distro versions which couldn’t build with native repos.
I’m fine if you add the ppa though. I think most people will use the -deb version anyway

2023-09-26 05:51 UTC, Zahrun commented
> Have you tested on supposed incompatible systems?

I will test these systems again

2023-09-26 07:34 UTC, Zahrun commented
Version 1.1.6 builds fine in jammy and is even compatible with obs 27, which was unexpected
![image](https://github.com/pacstall/pacstall-programs/assets/10415894/df785ac4-3ffc-4138-93cd-4f53c6888a92)

2023-09-26 10:24 UTC, Zahrun commented
Focal fails with "CMake Error: The source directory "/tmp/pacstall/obs-backgroundremoval-1.1.6/linux-ci-x86_64" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Error: /tmp/pacstall/obs-backgroundremoval-1.1.6/build_x86_64 is not a directory"
It has cmake 3.16.3 which is supposed to be compatible since https://github.com/royshil/obs-backgroundremoval/pull/250/files

2023-09-26 13:55 UTC, Zahrun requested changes

2023-09-26 13:55 UTC, Zahrun commented on packages/obs-backgroundremoval/obs-backgroundremoval.pacscript
>  incompatible=('*:jammy' '*:focal' '*:bionic' '*:buster' '*:bullseye')
```suggestion
incompatible=('*:focal' '*:bionic' '*:buster' '*:bullseye')
```

2023-09-26 14:26 UTC, umireon commented on packages/obs-backgroundremoval/obs-backgroundremoval.pacscript
> +  cmake --preset linux-ci-x86_64 -DCMAKE_INSTALL_PREFIX=/usr
I'm OK with linux-x86_64

2023-09-26 14:29 UTC, umireon commented
I don't think our plugin can be built with CMake 3.16.

2023-09-26 17:13 UTC, Zahrun commented
> I don't think our plugin can be built with CMake 3.16.

Should line 1 of CMakeList be updated? https://github.com/royshil/obs-backgroundremoval/blob/main/CMakeLists.txt#L1

2023-09-26 17:41 UTC, Zahrun approved these changes
Merge in from master for the checks not to fail

2023-09-26 21:30 UTC, Elsie19 commented
Ok it works, but do we want to try getting it working on all these distros or no?

2023-09-27 05:36 UTC, umireon commented
I don't know why the uninstalling test fails. Does this test need to be passed?

2023-09-27 06:14 UTC, Zahrun commented
> Ok it works, but do we want to try getting it working on all these distros or no?

It works on Ubuntu LTS and more recent, Debian stable, testing, and sid. I consider it’s good enough.

> I don't know why the uninstalling test fails. Does this test need to be passed?

This is only a CI issue due to the cmake-deb pacdep. We should be good to merge.

2023-09-27 11:48 UTC, Elsie19 approved these changes

2023-09-27 11:48 UTC, merged