Add grapejuice-git
pacstall/pacstall-programs pull request #468
Opened 2021-10-30 14:49 UTC by Henryws

2021-11-03 11:28 UTC, wizard-28 requested changes
Fix codacy issues first

2021-11-06 16:59 UTC, Henryws commented
> Fix codacy issues first

The AUR follows the exact same method of using a glob

2021-11-07 02:28 UTC, wizard-28 requested changes
No body said to remove the glob... Just put `./` in front of Mr. Glob

2021-11-08 05:38 UTC, wizard-28 requested changes
Add `breaks`, `gives`

---

Also does it have icons / desktop files? How is your script handling those?

2021-11-08 05:38 UTC, wizard-28 commented on packages/grapejuice-git/grapejuice-git.pacscript
> +  sudo tar -xf ./*.tar.gz -C /usr/src/pacstall/grapejuice-git/
```suggestion
  sudo tar -xf ./*.tar.gz -C /$STOWDIR/$name/
```

2021-11-08 05:38 UTC, wizard-28 commented on packages/grapejuice-git/grapejuice-git.pacscript
> +  sudo mkdir -p /usr/src/pacstall/grapejuice-git/
```suggestion
  sudo mkdir -p $STOWDIR/$name
```

2021-11-08 05:38 UTC, wizard-28 commented on packages/grapejuice-git/grapejuice-git.pacscript
> +  python3 -m grapejuice_packaging linux_package || python -m grapejuice_packaging linux_package
What is this line for?

2021-11-08 20:22 UTC, Henryws commented on packages/grapejuice-git/grapejuice-git.pacscript
> +  python3 -m grapejuice_packaging linux_package || python -m grapejuice_packaging linux_package
Just in case

2021-11-08 23:42 UTC, Henryws commented
> Add `breaks`, `gives`
> 
> Also does it have icons / desktop files? How is your script handling those?

The linux packaging part takes care of icons / desktop files

2021-11-09 05:24 UTC, wizard-28 requested changes

2021-11-09 05:24 UTC, wizard-28 commented on packages/grapejuice-git/grapejuice-git.pacscript
> +breaks="grapejuice grapejuice-bin"
Add the other types too

2021-11-09 05:24 UTC, wizard-28 commented on packages/grapejuice-git/grapejuice-git.pacscript
> +  sudo tar -xf ./*.tar.gz -C /$STOWDIR/$name/
```suggestion
  sudo tar -xf ./*.tar.gz -C "$STOWDIR/$name"
```

2021-11-09 05:24 UTC, wizard-28 commented on packages/grapejuice-git/grapejuice-git.pacscript
> +  sudo mkdir -p $STOWDIR/$name
```suggestion
  sudo mkdir -p "$STOWDIR/$name"
```

2021-11-09 17:08 UTC, wizard-28 approved these changes

2021-11-09 17:08 UTC, merged