add: `tdrop-git`
pacstall/pacstall-programs pull request #4683
Opened 2023-10-19 21:26 UTC by thomascrha

## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [x] Contact devs
- [x ] Add maintainer to pacscript

2023-10-20 00:33 UTC, Elsie19 requested changes

2023-10-20 00:33 UTC, Elsie19 commented on packages/tdrop-git/tdrop-git.pacscript
> +depends=("xdotool", "bash", "gawk", "procps-ng")
Remove the commas.

2023-10-22 01:01 UTC, thomascrha commented
Applogies for the force push - LazyGit just started doing it before I could respond. Anyway thats the commas removed.

2023-10-22 01:02 UTC, Elsie19 commented
Great! Can you pull from master so the CI will start working?

2023-10-22 01:07 UTC, thomascrha commented
Is that what you wanted ?

2023-10-22 01:08 UTC, Elsie19 commented
I meant from the GitHub interface 👀

2023-10-22 01:09 UTC, thomascrha commented
Do you want me throw this out and start again ? This branches history is now pretty messed up. I can squash it all down ?

2023-10-22 01:10 UTC, thomascrha commented
Closing this due to some git errors on my part - will open another pr to keep things clean.

2023-10-22 01:10 UTC, closed without merging