[Package Add] Microsoft Edge Stable (Deb)
pacstall/pacstall-programs pull request #480
Opened 2021-11-06 15:08 UTC by WRM-42

https://www.theverge.com/2021/11/2/22759123/microsoft-edge-linux-stable-channel

2021-11-06 15:10 UTC, Henryws approved these changes

2021-11-07 02:42 UTC, wizard-28 requested changes
Add `breaks`

2021-11-18 01:04 UTC, Henryws commented
ready for review?

2021-11-18 01:04 UTC, WRM-42 commented
> ready for review?
Yes

2021-11-18 01:04 UTC, Henryws approved these changes

2021-11-18 01:05 UTC, merged