add: `xdg-desktop-portal-hyprland`
pacstall/pacstall-programs pull request #4933
Opened 2023-11-21 23:41 UTC by oklopfer

2023-11-21 23:45 UTC, oklopfer commented
hang on this isn't working like how I tested it...

2023-11-23 18:23 UTC, merged

2023-11-23 19:19 UTC, Elsie19 requested changes

2023-11-23 19:19 UTC, Elsie19 commented on packages/xdg-desktop-portal-hyprland/xdg-desktop-portal-hyprland.pacscript
> +pkgrel="1"
```suggestion
```
Implicit.

2023-11-23 19:21 UTC, oklopfer commented on packages/xdg-desktop-portal-hyprland/xdg-desktop-portal-hyprland.pacscript
> +pkgrel="1"
the git child requires pkgrel.