Add: tailscale
pacstall/pacstall-programs pull request #4953
Opened 2023-11-25 08:24 UTC by ndowens

2023-11-25 19:53 UTC, Elsie19 requested changes
* Styling is wrong (run pre commit).
* packagelist isn't updated.
* Title also wrong.

2023-11-25 22:03 UTC, ndowens commented
What's the proper usage of pre-commit. When I run it just says skipped on each

2023-11-25 22:04 UTC, Elsie19 commented
Run `pre-commit -a`.

2023-11-28 05:53 UTC, Elsie19 commented
Fails on Debian stable and Ubuntu stable.

2023-11-29 08:19 UTC, ndowens commented
> Fails on Debian stable and Ubuntu stable.

From what I read, it seems because it is using an older go version

2023-11-29 13:27 UTC, Elsie19 requested changes

2023-11-29 13:27 UTC, Elsie19 commented on packages/tailscale/tailscale.pacscript
> +  export CGO_CPPFLAGS="${CPPFLAGS}"
these vars are empty, no?

2023-12-01 04:01 UTC, Elsie19 requested changes
![image](https://github.com/pacstall/pacstall-programs/assets/58742515/7ac8dc9c-a927-47eb-932e-09deee19592b)
Make all those fails into `incompatible` keys.

2023-12-02 21:31 UTC, oklopfer requested changes

2023-12-02 21:31 UTC, oklopfer commented on packages/tailscale/tailscale.pacscript
> +incompatible=('ubuntu:latest' 'debian:stable')
`ubuntu:latest` and `debian:stable` are identifiers for the GitHub builders themselves, the actual versions of those right now are `ubuntu:jammy` and `debian:bookworm`, you should change the array to these values.

2023-12-03 02:16 UTC, oklopfer approved these changes

2023-12-03 02:18 UTC, merged