add: `wgcf`
pacstall/pacstall-programs pull request #5166
Opened 2024-01-04 15:00 UTC by wildyrando

Adding wgcf to pacstall

2024-01-04 15:05 UTC, Elsie19 requested changes

2024-01-04 15:05 UTC, Elsie19 commented on packages/wgcf/wgcf.pacscript
> +pkgdesc="🚤 Cross-platform, unofficial CLI for Cloudflare Warp"
no emojis.

2024-01-04 15:12 UTC, wildyrando commented
Done, changed

2024-01-05 02:38 UTC, Elsie19 requested changes

2024-01-05 02:38 UTC, Elsie19 commented on packages/wgcf/wgcf.pacscript
> +  sudo mv wgcf "${pkgdir}/wgcf/usr/bin/"
You can make all these commands into one using `install`.

2024-01-05 04:35 UTC, wildyrando commented
Done, changed to using `install`

2024-01-05 04:35 UTC, Elsie19 requested changes

2024-01-05 04:35 UTC, Elsie19 commented on packages/wgcf/wgcf.pacscript
> +  sudo mkdir -p "${pkgdir}/usr/bin/"
you don't need this.

2024-01-05 17:10 UTC, wildyrando commented
Done, changed

2024-01-05 18:50 UTC, Elsie19 requested changes
This should be `wgcf-bin`.

2024-01-05 18:57 UTC, Elsie19 commented
change the package file name and path as well

2024-01-05 18:57 UTC, wildyrando commented
> This should be `wgcf-bin`.

Solved

2024-01-05 19:02 UTC, closed without merging