[Package add] vega-strike
pacstall/pacstall-programs pull request #532
Opened 2021-11-30 14:08 UTC by echometerain

2021-11-30 20:02 UTC, Henryws approved these changes

2021-12-01 04:07 UTC, wizard-28 commented
**DO NOT MERGE TILL #537 IS MERGED**

2021-12-05 08:22 UTC, wizard-28 requested changes
Follow the instructions to setup your pacscript development environment listed [here](https://github.com/pacstall/pacstall-programs#how-to-setup-the-environment-for-pacscript-development)

After doing so try staging (`git add`) this file (make a small dummy modification) then try to commit it (after running `pre-commit install`). When the pre-commit hooks fail (if they fail), fix the errors.

2021-12-06 16:03 UTC, wizard-28 requested changes

2021-12-06 16:03 UTC, wizard-28 commented on packages/vega-strike-engine-git/vega-strike-engine-git.pacscript
> +  cd build || exit
```suggestion
  cd build || return 1
```

2021-12-06 16:03 UTC, wizard-28 commented on packages/vega-strike-git/vega-strike-git.pacscript
> +    git ls-remote "${url}" master | cut -f1
Why is the indentation 4 spaces?

2021-12-06 16:03 UTC, wizard-28 commented on packages/vega-strike-engine-git/vega-strike-engine-git.pacscript
> +    git ls-remote "${url}" master | cut -f1
Why is the indentation 4 spaces?

2021-12-06 16:03 UTC, wizard-28 commented on packages/vega-strike-engine-git/vega-strike-engine-git.pacscript
> +  cd build || exit
```suggestion
  cd build || return 1
```

2021-12-06 18:02 UTC, wizard-28 commented on packages/vega-strike-engine-git/vega-strike-engine-git.pacscript
> +  sudo rm -rf "${STOWDIR}/${name}/usr/lib"
Umm... why?

2021-12-06 19:26 UTC, echometerain commented on packages/vega-strike-engine-git/vega-strike-engine-git.pacscript
> +  sudo rm -rf "${STOWDIR}/${name}/usr/lib"
AUR had this

2021-12-06 19:29 UTC, echometerain commented on packages/vega-strike-git/vega-strike-git.pacscript
> +  make
the makefile here doesn't actually build anything, it just moves some files

2021-12-06 21:08 UTC, echometerain commented on packages/vega-strike-engine-git/vega-strike-engine-git.pacscript
> +  cd ..
![image](https://user-images.githubusercontent.com/70437021/144922891-cd52c17d-c1dc-4978-a1e2-fa281e6974b4.png)

2021-12-07 01:57 UTC, wizard-28 requested changes

2021-12-07 01:57 UTC, wizard-28 commented on packages/vega-strike-git/vega-strike-git.pacscript
> +depends="make"
How does it depend on `make`

2021-12-07 04:11 UTC, wizard-28 approved these changes

2021-12-07 04:12 UTC, merged