add wazzapp-deb
pacstall/pacstall-programs pull request #553
Opened 2021-12-13 13:04 UTC by Zahrun

2021-12-13 14:43 UTC, Henryws requested changes

2021-12-13 14:43 UTC, Henryws commented on packages/wazzapp-deb/wazzapp-deb.pacscript
> +breaks="${pkgname} ${pkgname}-git ${pkgname}-bin ${pkgname}-app ${pkgname}-deb "
Remove extra space at the end

2021-12-13 15:33 UTC, wizard-28 requested changes
Same changes requested as https://github.com/pacstall/pacstall-programs/pull/554#pullrequestreview-830384065

2021-12-14 08:51 UTC, wizard-28 requested changes
Add `gives`

2021-12-14 09:01 UTC, wizard-28 approved these changes

2021-12-14 09:01 UTC, merged