Update stockfish-git.pacscript
pacstall/pacstall-programs pull request #5566
Opened 2024-01-28 21:19 UTC by pythoncrazy

I missed the key step of stripping the exectuable to make it smaller and faster, as well as using profile-build to do something good. This has been tested on my jetson xavier and jetson nano, so it will probably work. Thank y'all!

2024-01-28 21:20 UTC, Elsie19 commented
Fix the title.

2024-01-28 21:29 UTC, pythoncrazy commented
Title should be better

2024-01-28 22:13 UTC, Elsie19 requested changes

2024-01-28 22:13 UTC, Elsie19 commented on packages/stockfish-git/stockfish-git.pacscript
> +
```suggestion
```

2024-01-29 00:58 UTC, Elsie19 approved these changes

2024-01-29 00:59 UTC, merged