[Add Package] Lyrebird
pacstall/pacstall-programs pull request #56
Opened 2021-06-27 14:29 UTC by D-Brox

This PR adds `lyrebird`
Fixed dependencies and requests from previous PR

2021-06-27 15:44 UTC, D-Brox commented
The codacy analysis is saying it needs 2 spaces for the  list-item indend, but in the README there are already 2 spaces

2021-06-27 16:11 UTC, wizard-28 commented
> The codacy analysis is saying it needs 2 spaces for the list-item indend, but in the README there are already 2 spaces

Oh, Ignore it then.

2021-06-28 03:00 UTC, wizard-28 requested changes

2021-06-28 03:00 UTC, wizard-28 commented on packages/lyrebird/lyrebird.pacscript
> +pkgname="lyrebird"
```suggestion

```
Not needed as there are no extra suffixes like `-git` to this pacscript. And remember to refactor all instances of `pkgname` -> `name`

2021-06-28 13:45 UTC, wizard-28 approved these changes
Works!

2021-06-28 13:46 UTC, merged