add: `qogir-gtk-theme-bin`
pacstall/pacstall-programs pull request #564
Opened 2021-12-16 05:00 UTC by wizard-28

## Progress
- [x] Edit `packagelist`
- [ ] Add initial pacscript
- [ ] Contact devs
- [ ] Add `maintainer` to pacscript

Closes #241

2021-12-27 18:32 UTC, Henryws requested changes

2021-12-27 18:32 UTC, Henryws commented on packages/qogir-gtk-theme-bin/qogir-gtk-theme-bin.pacscript
> +    _INSTALL_OPTS="$(/usr/bin/grep --extended-regexp --max-count=1 --line-regexp --invert-match '^\s*$|#.+' /etc/qogir-gtk-theme/options.txt 2> /dev/null)"
Why is this a full path? Bash doesn't use aliases during a script, so simply running `grep` in a script will run wherever grep is in `PATH`

2021-12-28 08:51 UTC, wizard-28 commented on packages/qogir-gtk-theme-bin/qogir-gtk-theme-bin.pacscript
> +    _INSTALL_OPTS="$(/usr/bin/grep --extended-regexp --max-count=1 --line-regexp --invert-match '^\s*$|#.+' /etc/qogir-gtk-theme/options.txt 2> /dev/null)"
For security. Also the PKGBUILD does so. If you want I can remove it.

`¯\_(ツ)_/¯`


> In POSIX environments, the PATH environment variable is used to specify a set of
> standard locations that will be searched for the first matching named executable. While > convenient, this behavior may allow a malicious actor to exert control over a system.
> If they are able to adjust the contents of the PATH variable, or manipulate the file 
> system, then a bogus executable may be discovered in place of the desired one. This
> executable will be invoked with the user privileges of the Python process that spawned 
> it, potentially a highly privileged user.

---

Sources: [B607](https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html)

2021-12-28 15:52 UTC, Henryws approved these changes

2022-01-04 03:53 UTC, merged