add: `nautilus-open-in-blackbox-git`
pacstall/pacstall-programs pull request #5650
Opened 2024-02-21 15:31 UTC by Anifyuli

2024-02-22 06:18 UTC, vigress8 requested changes

2024-02-22 06:18 UTC, vigress8 commented on packages/nautilus-open-in-blackbox-git/nautilus-open-in-blackbox-git.pacscript
> +arch='any'
```suggestion
```
Unnecessary

2024-02-22 06:18 UTC, vigress8 commented on packages/nautilus-open-in-blackbox-git/nautilus-open-in-blackbox-git.pacscript
> +  cd "${name}-${pkgver}"
```suggestion
pkgver() {
  git ls-remote "${url}" main | cut -f1 | cut -c1-8
}
package() {
```

2024-02-23 01:45 UTC, Anifyuli commented on packages/nautilus-open-in-blackbox-git/nautilus-open-in-blackbox-git.pacscript
> +arch='any'
Done

2024-02-23 01:45 UTC, Anifyuli commented on packages/nautilus-open-in-blackbox-git/nautilus-open-in-blackbox-git.pacscript
> +  cd "${name}-${pkgver}"
It's done too

2024-02-24 06:05 UTC, Elsie19 requested changes

2024-02-24 06:05 UTC, Elsie19 commented on packages/nautilus-open-in-blackbox-git/nautilus-open-in-blackbox-git.pacscript
> +}
```suggestion
}

```

2024-02-25 22:56 UTC, Elsie19 requested changes

2024-02-25 22:56 UTC, Elsie19 commented on packages/nautilus-open-in-blackbox-git/nautilus-open-in-blackbox-git.pacscript
> +
```suggestion
```

2024-02-26 19:02 UTC, Elsie19 requested changes

2024-02-27 01:30 UTC, Elsie19 approved these changes

2024-02-27 01:30 UTC, merged