add(rustdesk-deb)
pacstall/pacstall-programs pull request #5666
Opened 2024-02-27 12:19 UTC by Xdavius

PacReq: rustdesk #5644

2024-02-27 14:25 UTC, Xdavius commented
@Elsie19 please, can you review ? it's my first add. thank you

2024-02-27 21:04 UTC, Elsie19 commented
Fix the title.

2024-02-27 21:13 UTC, Xdavius commented
> Fix the title.

Done

2024-02-27 21:17 UTC, Elsie19 requested changes

2024-02-27 21:17 UTC, Elsie19 commented on packages/rustdesk-deb/rustdesk-deb.pacscript
> +pkgdesc="Yet another remote desktop software, written in Rust."
```suggestion
pkgdesc="Yet another remote desktop software, written in Rust"
```

2024-02-28 02:02 UTC, Xdavius commented on packages/rustdesk-deb/rustdesk-deb.pacscript
> +pkgdesc="Yet another remote desktop software, written in Rust."
Done

2024-02-28 13:09 UTC, Elsie19 approved these changes

2024-02-28 13:09 UTC, merged