upd(prismlauncher-git):``7.2``->``8.0``
pacstall/pacstall-programs pull request #5667
Opened 2024-02-27 12:44 UTC by Xdavius

solve https://github.com/pacstall/pacstall-programs/issues/4679

2024-02-27 13:02 UTC, Xdavius commented
libqt6core5compat6-dev is for ubuntu 22.04
qt6-5compat-dev for all others

@Elsie19 : Can I set incompatible=(ubuntu:22.04) ?

I have tested with | seems not working

2024-02-27 13:12 UTC, Xdavius commented
> Can you conditionally check $DISTRO and use the correct names from there?

go reading the documentation =) and installing ubuntu

2024-02-27 13:38 UTC, Elsie19 requested changes
Move these all out of prepare().

2024-02-27 13:38 UTC, Elsie19 commented on packages/prismlauncher-git/prismlauncher-git.pacscript
> +case $VERSION_CODENAME in
```suggestion
case "${DISTRO}" in
```

2024-02-27 13:38 UTC, Elsie19 commented on packages/prismlauncher-git/prismlauncher-git.pacscript
> +sudo apt install -y libqt6core5compat6-dev
```suggestion
*:jammy)
  makedepends+=("libqt6core5compat6-dev")
```

2024-02-27 13:38 UTC, Elsie19 commented on packages/prismlauncher-git/prismlauncher-git.pacscript
> +sudo apt install -y qt6-5compat-dev
```suggestion
  makedepends+=("qt6-5compat-dev")
```

2024-02-27 21:04 UTC, Elsie19 commented
> I had trouble understanding all.
> 
> The documentation https://github.com/pacstall/pacstall/wiki/Pacscript-101 say : 
> 
> ```
> prepare() {
>   ./autogen.sh
>   case "${CARCH}" in
>     amd64) ;;
>     arm64) ;;
>     *) ;;
>   esac
>   case "${DISTRO}" in
>     ubuntu:*) ;;
>     debian:sid) ;;
>     *) ;;
>   esac
> }
> ```

https://github.com/pacstall/pacstall-programs/blob/master/packages%2Fhyprland%2Fhyprland.pacscript#L7-L11

2024-02-27 21:06 UTC, Elsie19 commented
Also run pre-commit. You should've done that already, it's listed in our setup instructions...

2024-02-27 21:22 UTC, Xdavius commented
> Also run pre-commit. You should've done that already, it's listed in our setup instructions...

I use github with the web interface... git from the terminal is not my friend. 
I have to do some extra efforts to learn it. 

Well, this time it's done I hope.

2024-02-27 21:37 UTC, Elsie19 commented
It's required that you run pre-commit.

2024-02-28 01:51 UTC, Xdavius commented
> It's required that you run pre-commit.

Ok. Understand what you are speaking about.

It's the tool that check the code when I do a PR (and use shellcheck and other things)

It has passed successfully.

So I don't understand why the label had changed to invalid here...

2024-02-28 01:53 UTC, Elsie19 commented
Ok run `shfmt -bn -ci -sr -s -i 2 -w packages/prismlauncher-git/prismlauncher-git.pacscript` and push it then.

2024-02-28 12:08 UTC, Xdavius commented
> Ok run `shfmt -bn -ci -sr -s -i 2 -w packages/prismlauncher-git/prismlauncher-git.pacscript` and push it then.

```davius@davius-gladius:~/pacstall-programs$ git config --global user.name "xdavius"
davius@davius-gladius:~/pacstall-programs$ git commit
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
check for added large files..............................................Passed
mixed line ending........................................................Passed
shellcheck...............................................................Passed
shfmt....................................................................Passed
update packagelist file..................................................Passed
[master f315fb48] upd(prismlauncher-git): `7.2`->`8.0`
 1 file changed, 11 insertions(+), 2 deletions(-)
davius@davius-gladius:~/pacstall-programs$ git push
remote: Permission to pacstall/pacstall-programs.git denied to Xdavius.
fatal : impossible d'accéder à 'https://github.com/pacstall/pacstall-programs.git/' : The requested URL returned error: 403
```

2024-02-28 13:10 UTC, Elsie19 commented
`git push origin HEAD`.

2024-02-29 15:03 UTC, Xdavius commented
> `git push origin HEAD`.

```
davius@davius-gladius:~/pacstall-programs$ git push origin HEAD
remote: Permission to pacstall/pacstall-programs.git denied to Xdavius.
fatal : impossible d'accéder à 'https://github.com/pacstall/pacstall-programs.git/' : The requested URL returned error: 403
```

2024-02-29 15:13 UTC, vigress8 commented
1) Create a fork (click on "Fork" on this repo's main page)
2) Clone it
3) If you haven't set up Git with your GitHub credentials, follow these instructions:
https://docs.github.com/en/get-started/getting-started-with-git/caching-your-github-credentials-in-git#github-cli
4) Create a branch and switch to it
```
git checkout -b <branchname>
```
4) Make your changes and commit them
5) Push
```
 git push -u origin <branchname>
```
6) A branch will be created in your fork, open a PR from there

2024-03-01 12:28 UTC, closed without merging

2024-03-01 12:45 UTC, vigress8 commented
> I don't understand this command  git push -u origin <branchname>. If I first create a branch, why I need to create an other ?

Because if you created the branch locally, then you need to push it to GitHub now.
-u is the short form of --set-upstream, so you're linking your local branch to a remote branch.

> Is it a way to PR directly from the terminal, or I need to turn to webUI ?
Yes, using `gh` : https://cli.github.com/manual/gh_pr_create

2024-03-02 00:50 UTC, Xdavius commented
> Why'd you close this?
I haven't

2024-03-02 00:51 UTC, Elsie19 commented
![image](https://github.com/pacstall/pacstall-programs/assets/58742515/ba56e181-c578-401a-9b58-4e8d4eff6799)

2024-03-02 01:28 UTC, Elsie19 commented
Wait there are two PRs..? #5680 and this one.