fix(neovide-bin): add app icons and entry
pacstall/pacstall-programs pull request #5717
Opened 2024-03-07 01:35 UTC by nezred

2024-03-07 21:39 UTC, Elsie19 requested changes

2024-03-07 21:39 UTC, Elsie19 commented on packages/neovide-bin/neovide-bin.pacscript
> +  do
Wrong formatting. Run it through shfmt like we require.

2024-03-07 21:39 UTC, Elsie19 commented on packages/neovide-bin/neovide-bin.pacscript
> +  do
Same.

2024-03-07 22:27 UTC, Elsie19 requested changes
Tabbing is still wrong. It should be 2 spaces.

2024-03-07 22:36 UTC, nezred reviewed
okay you are right, when running shfmt through vim with `:%!shfmt`, vim used tabs and not spaces for some reason.

2024-03-09 15:44 UTC, Elsie19 commented
Pull from master.

2024-03-11 04:27 UTC, Elsie19 approved these changes
Thanks for the PR!

2024-03-11 04:28 UTC, merged