add: `bottom-deb`
pacstall/pacstall-programs pull request #5720
Opened 2024-03-07 22:53 UTC by nezred

## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [ ] Contact devs
- [x] Add maintainer to pacscript

2024-03-09 15:45 UTC, Elsie19 commented
Pull from master.

2024-03-11 04:27 UTC, Elsie19 requested changes

2024-03-11 04:27 UTC, Elsie19 commented on packages/bottom-deb/bottom-deb.pacscript
> +homepage="https://clementtsang.github.io/${gives}/"
```suggestion
homepage='https://clementtsang.github.io/bottom'
```
Should be single quotes for `homepage`.

2024-03-11 04:27 UTC, Elsie19 commented on packages/bottom-deb/bottom-deb.pacscript
> +pkgdesc="A customizable cross-platform graphical process/system monitor for the terminal."
```suggestion
pkgdesc="A customizable cross-platform graphical process/system monitor for the terminal"
```

2024-05-18 08:31 UTC, oklopfer requested changes
Needs srcinfo generated. Run: 
```bash
./scripts/srcinfo.sh packages/bottom-deb/bottom-deb.pacscript
git add packages/bottom-deb/.SRCINFO
```

2024-05-24 21:30 UTC, oklopfer commented
superseded by https://github.com/pacstall/pacstall-programs/pull/6055

2024-05-24 21:30 UTC, closed without merging