add(packagelist): endlessh-git
pacstall/pacstall-programs pull request #577
Opened 2021-12-21 01:08 UTC by Henryws

## Progress
- [x] Edit `packagelist`
- [x] Add initial pacscript
- [ ] Contact devs: (dummy text)
- [ ] Add `maintainer` to pacscript

2021-12-21 06:08 UTC, wizard-28 requested changes
1. Add `gives` & `breaks`.
2. Use `pkgdir` instead.
3. Install `UNILICENSE` & `README.md`
4. Install the sample config file (download it from this repository)

2021-12-21 14:51 UTC, wizard-28 requested changes

2021-12-21 14:51 UTC, wizard-28 commented on packages/endlessh-git/endlessh-git.pacscript
> +	wget -q https://raw.githubusercontent.com/pacstall/pacstall-programs/master/packages/endlessh-git/sample-config
Verify checksum

2021-12-21 17:45 UTC, wizard-28 requested changes

2021-12-21 17:45 UTC, wizard-28 commented on packages/endlessh-git/endlessh-git.pacscript
> +  if ! [[ "$(sha256sum sample-config)" == "f92a2341103a7c6243d7cbc32a3400e0f01ecd5fae12a0731029f6c50ba9f451  sample-config" ]]; then
```suggestion
  if [[ "$(sha256sum sample-config | cut -d' ' -f 1)" != "f92a2341103a7c6243d7cbc32a3400e0f01ecd5fae12a0731029f6c50ba9f451" ]]; then
```

2021-12-21 18:02 UTC, wizard-28 commented on packages/endlessh-git/endlessh-git.pacscript
> +  # sha256sum f92a2341103a7c6243d7cbc32a3400e0f01ecd5fae12a0731029f6c50ba9f451
What's this comment for? I think a comment saying that it's downloading the sample config would be more helpful.

2021-12-22 08:09 UTC, wizard-28 requested changes

2021-12-22 08:09 UTC, wizard-28 commented on packages/endlessh-git/endlessh-git.pacscript
> +  sudo install -Dm644 UNLICENSE -t "${pkgdir}/usr/share/licenses/${name}"
Remove the empty directories in `removescript()`

2021-12-30 21:47 UTC, closed without merging

2021-12-30 21:49 UTC, Henryws commented
Messed up the git history accidentally, remaking the PR