upd(goverlay): `1.0` -> `1.1.1`
pacstall/pacstall-programs pull request #5774
Opened 2024-03-25 13:09 UTC by Xdavius

- Goverlay is full Qt6 from upstream (Thx to Antiz)
- Add pacdeps=("qt6pas")
- Changed URL to point to Source Package (Was binary before, without -bin)
- Is now built from source
- Changed maintainer name to Xdavius

2024-03-25 13:10 UTC, Xdavius commented
Need qt6pas merge before

2024-03-26 18:06 UTC, Elsie19 requested changes
Please don't plop in the PKGBUILD, try to rework the pacscript as is.

2024-03-26 21:17 UTC, Xdavius commented
> Please don't plop in the PKGBUILD, try to rework the pacscript as is.

Will see later.

Need to push again after qt6pas merge to check if some makedepends are missing too (wasn't on my side but...)

Ok for check function.

But still don't understand why cancelling pkgver line even if it's implicit. 

Please, wait a bit for this one.

I have re-uploaded you're original one as -git for now, without update, as an alternative before I test the -bin new release on my side (tempus fugit for now)

Thank you.

2024-03-26 21:18 UTC, Elsie19 commented
> But still don't understand why cancelling pkgver line even if it's implicit.

`pkgrel` defaults to `1` if not included, it only clutters it if you include it with it's default value.

2024-03-27 13:06 UTC, Xdavius commented on packages/goverlay/goverlay.pacscript
> +}
> shfmt.

It dosen't change anything.
here : I see 2 spaces
When I download, see a tab with 4 spaces

When run shfmt, see 4 spaces too.

2024-03-27 13:12 UTC, Xdavius commented on packages/goverlay/goverlay.pacscript
> +}
reinstalled pre-commit, now OK

2024-03-29 15:31 UTC, Xdavius commented
Need lazarus-ide > 3.0 as pacdeps to build.

Working on lazarus-ide-qt6 to provide it.

2024-03-30 13:51 UTC, Elsie19 commented
Please make this a draft until you are ready for review.

2024-03-30 17:02 UTC, Xdavius commented
> Please make this a draft until you are ready for review.

Should be good with lazarus-deb merged

2024-03-30 17:28 UTC, Elsie19 commented
All the tests fail.

2024-03-30 17:50 UTC, Xdavius commented
> All the tests fail.

I'm testing right now. lazarus-deb doesn't provide the default symlink... (No update-aternative, no postinstall in the Deb...)

And the package lazarus-deb doesn't support pacdeps so it doesn't download his deps... it's really a pain...

So... I need to fix this.

2024-03-30 17:52 UTC, Elsie19 commented
> And the package lazarus-deb doesn't support pacdeps so it doesn't download his deps... it's really a pain...

[We are working on that](https://github.com/pacstall/pacstall/pull/1062) for 5.0.0.

2024-03-30 18:14 UTC, Xdavius commented
> > And the package lazarus-deb doesn't support pacdeps so it doesn't download his deps... it's really a pain...
> 
> [We are working on that](https://github.com/pacstall/pacstall/pull/1062) for 5.0.0.

I have found a solution, puting deps in order in pacdeps...

But, I have a new error with Lazarus set as dep (but I have no more depend on my test copy... I should reinstall a clean VM to continue, after the weekend now)

2024-04-01 11:59 UTC, Xdavius commented
Hi.

I have modified my fork but, I see that if I modify it, update directly here. I don't want this but I don't know how to do. My branch is like synchonized to the PR.

2024-04-03 13:34 UTC, closed without merging