add: `flyctl-bin`
pacstall/pacstall-programs pull request #5850
Opened 2024-04-11 19:20 UTC by raindev

Add a package for the fly.io command line client

2024-04-11 20:53 UTC, Elsie19 requested changes

2024-04-11 20:53 UTC, Elsie19 commented on packages/flyctl-bin/flyctl-bin.pacscript
> +homepage="https://fly.io/"
```suggestion
homepage='https://fly.io'
```

2024-04-12 15:14 UTC, Elsie19 approved these changes

2024-04-12 15:15 UTC, merged

2024-04-12 15:17 UTC, oklopfer commented
Bruh I forgot to hit send

2024-04-12 18:15 UTC, raindev commented on packages/flyctl-bin/flyctl-bin.pacscript
> +    arch_suffix="amd64"
Thanks for noticing, that was sloppy of me. Fixed by Elsie in #5857.