[Package Add] Tachidesk
pacstall/pacstall-programs pull request #59
Opened 2021-06-29 12:59 UTC by D-Brox

This PR adds `tachidesk`

2021-06-30 02:52 UTC, wizard-28 requested changes
Is this a `-git` pacscript? You don't seem to be using any of the files cloned by git (except `LICENSE` etc), so why make it a `-git` pacscript?

2021-06-30 02:52 UTC, wizard-28 commented on packages/tachidesk/tachidesk.pacscript
> +depends=("openjdk-15-jre")
```suggestion
depends="openjdk-15-jre"
```
`depends` is not an array iirc.

2021-06-30 03:21 UTC, D-Brox commented
> Is this a `-git` pacscript? You don't seem to be using any of the files cloned by git (except `LICENSE` etc), so why make it a `-git` pacscript?

True, it doesn't really need to be a `-git`, I probably forgot to change it, since I just altered my `tachidesk-jui` script, which really needs to be a `-git` pacscript.

Should I just use `wget` to get the `README` and `LICENSE` files, and should I just remove the `.git` from the url?

2021-06-30 10:42 UTC, wizard-28 commented
I don't think just downloading the `.jar` using `url` will work (check the CI) @Henryws needs to take a look here.

2021-06-30 12:52 UTC, Henryws commented
It won't work. It will try to untar it

2021-07-01 22:52 UTC, D-Brox commented
Speaking of which, I guess Pacstall should also deal with cases where there is no extension at the end of the url, since some packages can be bash scrips or executables (youtube-dl and czkawka, for example). I'll open an issue for feature reques later. For now I'll close this PR.

2021-07-01 22:52 UTC, closed without merging