upd(neofetch): modernize
pacstall/pacstall-programs pull request #602
Opened 2022-01-02 02:54 UTC by Henryws

2022-01-02 08:15 UTC, wizard-28 requested changes
Add `maintainer`

2022-01-03 06:54 UTC, wizard-28 requested changes
Where is `name`?

2022-01-03 15:53 UTC, Henryws commented
It's there, view the entire file.

2022-01-04 03:56 UTC, wizard-28 approved these changes

2022-01-04 03:56 UTC, merged