add: 'teams-for-linux-deb'
pacstall/pacstall-programs pull request #603
Opened 2022-01-02 11:43 UTC by Zahrun

2022-01-02 12:02 UTC, wizard-28 commented
@Henryws, I don't think we could do the procedures (contacting dev) here. So we shall skip them right?

2022-01-02 12:03 UTC, wizard-28 requested changes

2022-01-02 12:03 UTC, wizard-28 commented on packages/teams-for-linux-deb/teams-for-linux-deb.pacscript
> +maintainer="Zahrun@github.com"
```suggestion
maintainer="Zahrun <Zahrun@github.com>"
```

2022-01-02 12:03 UTC, wizard-28 commented on packages/teams-for-linux-deb/teams-for-linux-deb.pacscript
> +breaks="${pkgname} ${pkgname}-git ${pkgname}-bin ${pkgname}-app ${pkgname}-deb"
```suggestion
breaks="${pkgname} ${pkgname}-git ${pkgname}-bin ${pkgname}-app"
```

2022-01-02 14:36 UTC, wizard-28 requested changes
Follow the new PR guidelines (it's has not been added to `CONTRIBUTING.md` yet). See #558, #567 for examples.

2022-01-03 06:49 UTC, wizard-28 commented
Okay, so now we wait max. 1 week for the dev to reply, if they don't within that time frame, then we merge

2022-01-04 09:51 UTC, wizard-28 requested changes
@Zahrun, add yourself as the maintainer

2022-01-04 10:23 UTC, wizard-28 requested changes

2022-01-04 10:23 UTC, wizard-28 commented on packages/teams-for-linux-deb/teams-for-linux-deb.pacscript
> +breaks="${pkgname} ${pkgname}-git ${pkgname}-bin ${pkgname}-app ${pkgname}-deb"
```suggestion
breaks="${pkgname} ${pkgname}-git ${pkgname}-bin ${pkgname}-app"
```

2022-01-04 10:33 UTC, Zahrun commented
Do we have a color to use with a pacstall badge like AUR has blue?
[![AUR: teams-for-linux](https://img.shields.io/badge/AUR-teams--for--linux-blue.svg)](https://aur.archlinux.org/packages/teams-for-linux)
https://shields.io/

2022-01-04 12:25 UTC, wizard-28 commented
> Do we have a color to use with a pacstall badge like AUR has blue? [![AUR: teams-for-linux](https://camo.githubusercontent.com/30a97ed381ee4a2ce479c0e6047a21fd65241123bd8908d67ce4767332468b40/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4155522d7465616d732d2d666f722d2d6c696e75782d626c75652e737667)](https://aur.archlinux.org/packages/teams-for-linux) https://shields.io/

Use `#00958C`

2022-01-04 12:39 UTC, Zahrun commented
Nice! 
[![Pacstall: teams-for-linux-deb](https://img.shields.io/badge/Pacstall-teams--for--linux--deb-00958C)](https://github.com/pacstall/pacstall-programs/tree/master/packages/teams-for-linux-deb)

2022-01-04 12:41 UTC, wizard-28 commented
> Nice! [![Pacstall: teams-for-linux-deb](https://camo.githubusercontent.com/5aafcad0603d5c09087a9286cd439f7a5f69e3070dc98e8285f4ccb8b5b66eef/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5061637374616c6c2d7465616d732d2d666f722d2d6c696e75782d2d6465622d303039353843)](https://github.com/pacstall/pacstall-programs/tree/master/packages/teams-for-linux-deb)

So, I should merge this first right?

2022-01-04 12:42 UTC, Zahrun commented
Yes, so that the link will direct to the package

2022-01-04 12:42 UTC, merged