add: `davinci-resolve`
pacstall/pacstall-programs pull request #6031
Opened 2024-05-19 15:49 UTC by vigress8

2024-05-19 15:54 UTC, vigress8 commented
Package seems to be too large for the runners. It works on my machine

2024-05-21 00:12 UTC, oklopfer commented
I need elsie to review this one bc of its sussiness

2024-05-24 04:03 UTC, Elsie19 commented
> I need elsie to review this one bc of its sussiness

Ok.

2024-05-24 04:06 UTC, Elsie19 requested changes

2024-05-24 04:06 UTC, Elsie19 commented on packages/davinci-resolve/davinci-resolve.pacscript
> +	  "email": "someone@pacstall.dev",
```suggestion
	  "email": "pacstall@pm.me",
```

2024-05-27 04:15 UTC, Elsie19 approved these changes

2024-05-27 04:15 UTC, merged