add: `dolphin-emu-git`
pacstall/pacstall-programs pull request #6067
Opened 2024-05-31 20:15 UTC by oklopfer

2024-05-31 20:32 UTC, oklopfer commented
needs a desktop file

2024-06-01 23:59 UTC, Elsie19 requested changes

2024-06-01 23:59 UTC, Elsie19 commented on packages/dolphin-emu-git/dolphin-emu-git.pacscript
> +pkgdesc='Dolphin is an emulator for running GameCube and Wii games'
Don't include the name of the package as the first word. Maybe do `Emulator for running GameCube and Wii games`.

2024-06-02 01:47 UTC, Elsie19 approved these changes

2024-06-02 01:50 UTC, merged