add: `distrobox-git`
pacstall/pacstall-programs pull request #6132
Opened 2024-06-17 09:03 UTC by Xdavius

2024-06-19 23:07 UTC, Elsie19 requested changes

2024-06-19 23:07 UTC, Elsie19 commented on packages/distrobox-git/distrobox-git.pacscript
> +maintainer="xdavius <xdavius@github.com>"
```suggestion
maintainer=("xdavius <xdavius@github.com>")
```

2024-06-19 23:07 UTC, Elsie19 commented on packages/distrobox-git/distrobox-git.pacscript
> +gives="distrobox-git"
```suggestion
gives="distrobox"
```

2024-06-19 23:07 UTC, Elsie19 commented on packages/distrobox-git/distrobox-git.pacscript
> +pkgdesc="Use any linux distribution inside your terminal."
```suggestion
pkgdesc="Use any linux distribution inside your terminal"
```

2024-06-19 23:07 UTC, Elsie19 commented on packages/distrobox-git/distrobox-git.pacscript
> +url="https://github.com/89luca89/distrobox"
```suggestion
url='https://github.com/89luca89/distrobox'
```

2024-06-19 23:07 UTC, Elsie19 commented on packages/distrobox-git/distrobox-git.pacscript
> +source=("${pkgname%-git}::git+${url}")
Use the full URL please.

2024-06-19 23:07 UTC, Elsie19 commented on packages/distrobox-git/distrobox-git.pacscript
> +}
```suggestion
```

2024-06-22 16:31 UTC, oklopfer commented on packages/distrobox-git/distrobox-git.pacscript
> +source=("${pkgname%-git}::git+${url}")
?

2024-06-22 16:36 UTC, vigress8 commented on packages/distrobox-git/distrobox-git.pacscript
> +source=("${pkgname%-git}::git+${url}")
Another Elsie brainworm

2024-06-26 19:20 UTC, Elsie19 approved these changes

2024-06-26 19:20 UTC, merged