add: `freshfetch-git`
pacstall/pacstall-programs pull request #6136
Opened 2024-06-17 21:16 UTC by pythoncrazy

I want to add freshfetch-git, for some reason it errors out on my ARM testing system, but works across the ~5 Ubuntu based distros running x86_64. If you have any advice/fixes, they would be very much appreciated.

2024-06-19 03:04 UTC, Elsie19 commented
What error is is on ARM?

2024-06-20 20:05 UTC, pythoncrazy commented
Some error with the faccess crate, I am not sure how to fix it: 

```error[E0308]: mismatched types
    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/faccess-0.2.3/src/lib.rs:95:36
     |
95   |             if faccessat(AT_FDCWD, path.as_ptr() as *const i8, mode, AT_EACCESS) == 0 {
     |                ---------           ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
     |                |
     |                arguments to this function are incorrect
     |
     = note: expected raw pointer `*const u8`
                found raw pointer `*const i8`
note: function defined here
    --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.104/src/unix/linux_like/linux/mod.rs:3738:12
     |
3738 |     pub fn faccessat(
     |            ^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `faccess` (lib) due to previous error

2024-06-26 19:36 UTC, Elsie19 requested changes

2024-06-26 19:36 UTC, Elsie19 commented on packages/freshfetch-git/freshfetch-git.pacscript
> +  cd "${_archive}"
Stop using _archive, use `"${gives}"` or `"freshfetch"`.

2024-06-26 20:47 UTC, pythoncrazy commented on packages/freshfetch-git/freshfetch-git.pacscript
> +  cd "${_archive}"
Alright, will do

2024-07-02 16:39 UTC, Elsie19 requested changes

2024-07-02 16:39 UTC, Elsie19 commented on packages/freshfetch-git/freshfetch-git.pacscript
> +url="https://github.com/K4rakara/freshfetch"
```suggestion
url='https://github.com/K4rakara/freshfetch'
```

2024-07-02 16:39 UTC, Elsie19 commented on packages/freshfetch-git/freshfetch-git.pacscript
> +  cargo build --release -vv
```suggestion
  cargo build --locked --release -vv
```

2024-07-04 13:52 UTC, Elsie19 approved these changes

2024-07-04 13:53 UTC, merged