Add waynergy pacscript.
pacstall/pacstall-programs pull request #6144
Opened 2024-06-19 23:40 UTC by erenfro

Adds waynergy to pacstall packages. A synergy, barrier, input-leap compatible waynergy-specific client.

2024-06-20 06:48 UTC, vigress8 requested changes

2024-06-20 06:48 UTC, vigress8 commented on packages/waynergy/waynergy.pacscript
> +  ninja -C build
```suggestion
  ninja -C build -j"${NCPU}"
```
To utilize all CPU threads for the build.

2024-06-20 06:48 UTC, vigress8 commented on packages/waynergy/waynergy.pacscript
> +pkgrel=3
```suggestion
```

2024-06-20 16:52 UTC, Elsie19 commented
Fix the title to conform to our standards, as explained in [our docs](https://github.com/pacstall/pacstall/wiki/101.5-Maintaining-a-Package#updating-your-package). You can also look at [past PRs](https://github.com/pacstall/pacstall-programs/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+label%3A%22Update+Package%22) to get an idea of how to format the title if you're unsure.

---

<img src="https://github.com/pacstall/pacstall-programs/assets/104327997/00a078f3-526b-48f1-b4ce-30499cd01123" alt="You gotta play by the rules" width="200"/>

2024-06-20 17:01 UTC, erenfro commented
> Fix the title to conform to our standards, as explained in [our docs](https://github.com/pacstall/pacstall/wiki/101.5-Maintaining-a-Package#updating-your-package). You can also look at [past PRs](https://github.com/pacstall/pacstall-programs/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+label%3A%22Update+Package%22) to get an idea of how to format the title if you're unsure.

All I'm seeing here is for updated packages, not for new packages being added. So this is not really entirely clear.

2024-06-22 21:30 UTC, oklopfer approved these changes

2024-06-22 21:30 UTC, merged