add: `restic-bin`
pacstall/pacstall-programs pull request #6150
Opened 2024-06-24 06:13 UTC by erenfro

restic backup program, binary distribution form that's compatible with most available arch's, but also may be newer than distribution-provided version for improved stability and security.

2024-06-26 15:38 UTC, erenfro commented
This is fully tested and ready for merging.

2024-06-26 19:22 UTC, Elsie19 requested changes

2024-06-26 19:22 UTC, Elsie19 commented on packages/restic-bin/restic-bin.pacscript
> +url="https://github.com/restic/restic"
```suggestion
url='https://github.com/restic/restic'
```

2024-06-26 19:22 UTC, Elsie19 commented on packages/restic-bin/restic-bin.pacscript
> +  # Install binary
```suggestion
```

2024-06-29 15:06 UTC, Elsie19 approved these changes

2024-06-29 15:06 UTC, merged