add: `resticprofile-bin`
pacstall/pacstall-programs pull request #6151
Opened 2024-06-24 06:39 UTC by erenfro

Configuration profiles manager for restic backup.

2024-06-26 15:39 UTC, erenfro commented
This is fully tested and ready for merging.

2024-06-26 19:23 UTC, Elsie19 requested changes

2024-06-26 19:23 UTC, Elsie19 commented on packages/resticprofile-bin/resticprofile-bin.pacscript
> +  # Install binary
```suggestion
```

2024-06-26 19:23 UTC, Elsie19 commented on packages/resticprofile-bin/resticprofile-bin.pacscript
> +url="https://github.com/creativeprojects/resticprofile"
```suggestion
url='https://github.com/creativeprojects/resticprofile'
```

2024-06-29 15:19 UTC, Elsie19 approved these changes

2024-06-29 15:20 UTC, Elsie19 submitted a review, later dismissed

2024-06-29 15:20 UTC, Elsie19 commented
Oops, I did it twice 😁

2024-06-29 15:21 UTC, Elsie19 commented
Fix the merge conflicts then I can merge.

2024-06-29 17:40 UTC, closed without merging