add: `grub-btrfs`
pacstall/pacstall-programs pull request #6152
Opened 2024-06-24 14:25 UTC by erenfro

Include btrfs snapshots in GRUB boot options

2024-06-26 15:39 UTC, erenfro commented
This is fully tested and ready for merging.

2024-06-26 19:24 UTC, Elsie19 requested changes

2024-06-26 19:24 UTC, Elsie19 commented on packages/grub-btrfs/grub-btrfs.pacscript
> +arch=('any')
```suggestion
```

`arch=('any')` is implicit if not included.

2024-06-26 19:24 UTC, Elsie19 commented on packages/grub-btrfs/grub-btrfs.pacscript
> +url="https://github.com/Antynea/${pkgname}"
```suggestion
url='https://github.com/Antynea/grub-btrfs'
```

2024-06-29 15:22 UTC, Elsie19 requested changes

2024-06-29 15:22 UTC, Elsie19 commented on packages/grub-btrfs/grub-btrfs.pacscript
> +backup=('etc/default/grub-btrfs/config')
anything in /etc automatically is considered a config file, so this like is redundant.

2024-07-01 23:41 UTC, oklopfer approved these changes

2024-07-01 23:42 UTC, merged