add: `btrfs-assistant`
pacstall/pacstall-programs pull request #6153
Opened 2024-06-24 15:07 UTC by erenfro

An application for managing BTRFS subvolumes and Snapper snapshots

2024-06-26 15:39 UTC, erenfro commented
This is fully tested and ready for merging.

2024-06-26 19:26 UTC, Elsie19 requested changes

2024-06-26 19:26 UTC, Elsie19 commented on packages/btrfs-assistant/btrfs-assistant.pacscript
> +url="https://gitlab.com/${pkgname}/${pkgname}"
```suggestion
url='https://gitlab.com/btrfs-assistant/btrfs-assistant'
```

2024-06-26 19:26 UTC, Elsie19 commented on packages/btrfs-assistant/btrfs-assistant.pacscript
> +pkgdesc="An application for managing BTRFS subvolumes and Snapper snapshots"
```suggestion
pkgdesc="Manage BTRFS subvolumes and Snapper snapshots"
```

2024-07-01 23:42 UTC, oklopfer approved these changes

2024-07-01 23:42 UTC, merged