add: `snapper-rollback-git`
pacstall/pacstall-programs pull request #6158
Opened 2024-06-26 05:18 UTC by erenfro

Script to rollback snapper snapshots as described here https://wiki.archlinux.org/index.php/Snapper#Suggested_filesystem_layout

2024-06-26 15:42 UTC, erenfro commented
This is fully tested and ready for merging.

2024-06-26 19:37 UTC, Elsie19 requested changes

2024-06-26 19:37 UTC, Elsie19 commented on packages/snapper-rollback-git/snapper-rollback-git.pacscript
> +pkgdesc='Script to rollback snapper snapshots as described here https://wiki.archlinux.org/index.php/Snapper#Suggested_filesystem_layout'
```suggestion
pkgdesc='Rollback snapper snapshots
https://wiki.archlinux.org/index.php/Snapper#Suggested_filesystem_layout'
```

2024-06-26 19:37 UTC, Elsie19 commented on packages/snapper-rollback-git/snapper-rollback-git.pacscript
> +arch=('any')
```suggestion
```

2024-06-26 19:37 UTC, Elsie19 commented on packages/snapper-rollback-git/snapper-rollback-git.pacscript
> +  cd "${_archive}"
Do not use _archive.

2024-06-29 15:05 UTC, Elsie19 requested changes

2024-06-29 15:05 UTC, Elsie19 commented on packages/snapper-rollback-git/snapper-rollback-git.pacscript
> +pkgver=1.0
Quote these.

2024-07-01 23:48 UTC, oklopfer approved these changes

2024-07-01 23:48 UTC, merged