add: `xdg-terminal-exec-git`
pacstall/pacstall-programs pull request #6187
Opened 2024-07-02 12:38 UTC by Xdavius

2024-07-02 13:49 UTC, Elsie19 requested changes

2024-07-02 13:49 UTC, Elsie19 commented on packages/xdg-terminal-exec-git/xdg-terminal-exec-git.pacscript
> +  cd "${_archive}"
Do not use `${_archive}`.

2024-07-02 13:50 UTC, Xdavius commented on packages/xdg-terminal-exec-git/xdg-terminal-exec-git.pacscript
> +  cd "${_archive}"
> Do not use `${_archive}`.

??

2024-07-02 14:07 UTC, Xdavius commented on packages/xdg-terminal-exec-git/xdg-terminal-exec-git.pacscript
> +  cd "${_archive}"
done

2024-07-02 16:38 UTC, Elsie19 requested changes

2024-07-02 16:38 UTC, Elsie19 commented on packages/xdg-terminal-exec-git/xdg-terminal-exec-git.pacscript
> +url='https://github.com/Vladimir-csp'
```suggestion
url='https://github.com/Vladimir-csp/xdg-terminal-exec'
```

2024-07-02 16:38 UTC, Elsie19 commented on packages/xdg-terminal-exec-git/xdg-terminal-exec-git.pacscript
> +source=("git+${url}/${gives}")
```suggestion
source=("git+https://github.com/Vladimir-csp/xdg-terminal-exec")
```

2024-07-03 02:41 UTC, Elsie19 approved these changes

2024-07-03 02:41 UTC, merged