add: `setconf`
pacstall/pacstall-programs pull request #6210
Opened 2024-07-08 05:57 UTC by Xdavius

2024-07-10 13:28 UTC, Elsie19 requested changes

2024-07-10 13:28 UTC, Elsie19 commented on packages/setconf/setconf.pacscript
> +arch=("any")
```suggestion
```

2024-07-10 13:46 UTC, Elsie19 requested changes

2024-07-10 13:46 UTC, Elsie19 commented on packages/setconf/setconf.pacscript
> +  'SKIP')
```suggestion
sha256sums=('19315574540b3181fec31a4059b9e058381e0192317f153d181e7e7e2aa84d86' 'SKIP')
```

2024-07-10 14:35 UTC, Xdavius commented on packages/setconf/setconf.pacscript
> +  'SKIP')
There are 2 sources.

2024-07-11 00:28 UTC, oklopfer requested changes

2024-07-11 00:28 UTC, oklopfer commented on packages/setconf/setconf.pacscript
> +validpgpkeys=('962855F072C7A01846405864FCF3C8CB5CF9C8D4')
we dont use this variable

2024-07-11 00:28 UTC, oklopfer commented on packages/setconf/setconf.pacscript
> +source=("https://setconf.roboticoverlords.org/${pkgname}-${pkgver}.tar.xz"{,.asc})
is the signature even needed?

2024-07-11 01:16 UTC, Xdavius commented
No more .asc
No more key.

2024-07-12 14:04 UTC, Elsie19 approved these changes

2024-07-12 14:04 UTC, merged