add: `it87-dkms-git`
pacstall/pacstall-programs pull request #6237
Opened 2024-07-13 12:17 UTC by Xdavius

2024-07-15 13:49 UTC, Elsie19 requested changes

2024-07-15 13:49 UTC, Elsie19 commented on packages/it87-dkms-git/it87-dkms-git.pacscript
> +}
```suggestion
```

2024-07-15 13:49 UTC, Elsie19 commented on packages/it87-dkms-git/it87-dkms-git.pacscript
> +
```suggestion
```

2024-07-15 13:49 UTC, Elsie19 commented on packages/it87-dkms-git/it87-dkms-git.pacscript
> +
```suggestion
```

2024-07-17 22:25 UTC, oklopfer approved these changes

2024-07-17 22:26 UTC, merged