upd(libdrm): `2.4.120` -> `2.4.122`
pacstall/pacstall-programs pull request #6274
Opened 2024-07-22 12:26 UTC by Xdavius

fixed installdir to /usr/local do avoid conflicts with libdrm2 and all mesa stuffs...

2024-07-23 19:29 UTC, oklopfer commented
Can you clarify why this *shouldn’t* be conflicting with those packages? It is my understanding that this package is equal to multiple different debs. I don’t think we should be changing to dir to /usr/local

2024-07-23 19:29 UTC, oklopfer requested changes
last thing was meant to be a review comment

2024-07-24 14:06 UTC, Xdavius commented
> Can you clarify why this _shouldn’t_ be conflicting with those packages? It is my understanding that this package is equal to multiple different debs. I don’t think we should be changing to dir to /usr/local

because it breaks all the dependency cascade in /usr : 
https://packages.debian.org/fr/sid/libdrm-dev
https://deb.debian.org/debian/pool/main/libd/libdrm/libdrm_2.4.121-2.dsc

```Binary: libdrm-dev, libdrm2, libdrm-common, libdrm-tests, libdrm2-udeb, libdrm-intel1, libdrm-nouveau2, libdrm-radeon1, libdrm-omap1, libdrm-freedreno1, libdrm-exynos1, libdrm-tegra0, libdrm-amdgpu1, libdrm-etnaviv1```

If you can replace all of theses without breaking something, I need to learn how because I don't know how to solve this. 
If I can be sure that provides work, it's the solution.

2024-07-24 14:10 UTC, Xdavius commented
In fact, I need to also provides I suppose to solve the cascade. and it should work in /usr also.

I update the provides but, tell me what you think about this.

2024-07-24 14:17 UTC, Xdavius commented
```
The following packages will be REMOVED:
  fastfetch glffetch-git libdrm-amdgpu1 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libdrm2 libegl-dev libegl-mesa0 libegl1 libegl1-mesa libgbm1
  libgl-dev libgl1 libgl1-mesa-dri libgl1-mesa-glx libglx-dev libglx-mesa0 libglx0 libosmesa6-dev mesa-vulkan-drivers
0 upgraded, 0 newly installed, 21 to remove and 0 not upgraded.
After this operation, 82.6 MB disk space will be freed.
(Reading database ... 55186 files and directories currently installed.)
Removing glffetch-git (1.0-pacstall1~git34ee3c6e) ...
Removing fastfetch (2.9.1-pacstall1~git5b76a0b4) ...
Do you want to remove the configuration files? [Y/n] 
Do you want to remove the left over cache? [Y/n] 
Removing mesa-vulkan-drivers:amd64 (22.3.6-1+deb12u1) ...
Removing libosmesa6-dev:amd64 (22.3.6-1+deb12u1) ...
Removing libegl-dev:amd64 (1.6.0-1) ...
Removing libegl1-mesa:amd64 (22.3.6-1+deb12u1) ...
Removing libegl1:amd64 (1.6.0-1) ...
Removing libegl-mesa0:amd64 (22.3.6-1+deb12u1) ...
Removing libgbm1:amd64 (22.3.6-1+deb12u1) ...
Removing libgl1-mesa-glx:amd64 (22.3.6-1+deb12u1) ...
Removing libgl-dev:amd64 (1.6.0-1) ...
Removing libgl1:amd64 (1.6.0-1) ...
Removing libglx-dev:amd64 (1.6.0-1) ...
Removing libglx0:amd64 (1.6.0-1) ...
Removing libglx-mesa0:amd64 (22.3.6-1+deb12u1) ...
Removing libgl1-mesa-dri:amd64 (22.3.6-1+deb12u1) ...
Removing libdrm-amdgpu1:amd64 (2.4.114-1+b1) ...
Removing libdrm-intel1:amd64 (2.4.114-1+b1) ...
Removing libdrm-nouveau2:amd64 (2.4.114-1+b1) ...
Removing libdrm-radeon1:amd64 (2.4.114-1+b1) ...
Removing libdrm2:amd64 (2.4.114-1+b1) ...
Processing triggers for libc-bin (2.36-9+deb12u7) ...
This script replaces libdrm-common. Do you want to proceed? [Y/n] 
```

2024-07-24 14:28 UTC, Xdavius commented
with --prefix=/usr/local

```
The following NEW packages will be installed:
  libdrm-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/423 kB of archives.
After this operation, 1348 kB of additional disk space will be used.
Get:1 /usr/src/pacstall/libdrm_2.4.122-pacstall1_amd64.deb libdrm-dev amd64 2.4.122-pacstall1 [423 kB]
Selecting previously unselected package libdrm-dev.
(Reading database ... 55766 files and directories currently installed.)
Preparing to unpack .../libdrm_2.4.122-pacstall1_amd64.deb ...
Unpacking libdrm-dev (2.4.122-pacstall1) ...
Setting up libdrm-dev (2.4.122-pacstall1) ...
Processing triggers for man-db (2.11.2-2) ...
[+] INFO: Performing post install operations
        [>] Storing pacscript
[+] INFO: Done installing libdrm
[+] INFO: Cleaning up
davius@distrobox-davius-debian ~/CLONES/pacstall-programs/packages/libdrm $ sudo apt list | grep libdrm2

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libdrm2/stable,now 2.4.114-1+b1 amd64  [installé, automatique]
```

2024-07-24 22:12 UTC, oklopfer requested changes

2024-07-24 22:12 UTC, oklopfer commented on packages/libdrm/libdrm.pacscript
> -    -D valgrind=disabled \
Please re-disable these

2024-07-25 17:08 UTC, oklopfer requested changes

2024-07-25 17:08 UTC, oklopfer commented on packages/libdrm/libdrm.pacscript
> +arch=("amd64")
why was arm64 support removed? We need to keep it

2024-07-25 18:14 UTC, oklopfer requested changes

2024-07-25 18:14 UTC, oklopfer commented on packages/libdrm/libdrm.pacscript
> +  depends="${pkgbase}"
needs parentheses

2024-08-10 20:14 UTC, oklopfer approved these changes

2024-08-10 20:14 UTC, merged