[Package Add] Clib
pacstall/pacstall-programs pull request #63
Opened 2021-07-03 20:03 UTC by D-Brox

Adds `clib`, the  C package manager-ish

2021-07-04 02:14 UTC, wizard-28 requested changes
Also edit `packagelist`

2021-07-05 04:04 UTC, wizard-28 requested changes

2021-07-06 04:01 UTC, wizard-28 commented on packages/clib/clib.pacscript
> +  sudo make
Why `sudo make`?

2021-07-06 04:09 UTC, D-Brox commented on packages/clib/clib.pacscript
> +  sudo make
My mistake, only `make install` needs sudo

2021-07-06 05:47 UTC, wizard-28 requested changes

2021-07-06 05:47 UTC, wizard-28 commented on packages/clib/clib.pacscript
> +  make
```suggestion
  make -j"${nproc}"
```
Use all cores

2021-07-07 11:54 UTC, wizard-28 approved these changes

2021-07-07 11:55 UTC, merged