update apx-git to 2.4.3
pacstall/pacstall-programs pull request #6394
Opened 2024-09-05 07:43 UTC by souhaiebtar

2024-09-05 07:55 UTC, souhaiebtar commented
the problem is not related to the package but some golang package can't be download throw proxy,

"dial tcp: lookup proxy.golang.org on 127.0.0.11:53: read udp "

2024-09-05 19:53 UTC, Xdavius commented
> the problem is not related to the package but some golang package can't be download throw proxy,
> 
> "dial tcp: lookup proxy.golang.org on 127.0.0.11:53: read udp "

add this variable to the pacscript 

`external_connection=true`

https://github.com/pacstall/pacstall-programs/pull/6383#issuecomment-2326516390

This script wasn't maintained...

2024-09-06 09:42 UTC, souhaiebtar reviewed
update to allow package access to internet during installation

2024-09-06 09:43 UTC, souhaiebtar commented
> > the problem is not related to the package but some golang package can't be download throw proxy,
> > "dial tcp: lookup proxy.golang.org on 127.0.0.11:53: read udp "
> 
> add this variable to the pacscript
> 
> `external_connection=true`
> 
> [#6383 (comment)](https://github.com/pacstall/pacstall-programs/pull/6383#issuecomment-2326516390)
> 
> This script wasn't maintained. It may need some adjustments.

think you, i made a change as advised to allow package access to internet during installation

2024-09-07 14:04 UTC, Elsie19 commented
Fix the title to conform to our standards, as explained in [our docs](https://github.com/pacstall/pacstall/wiki/101.5-Maintaining-a-Package#updating-your-package). You can also look at [past PRs](https://github.com/pacstall/pacstall-programs/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+label%3A%22Update+Package%22) to get an idea of how to format the title if you're unsure.

---

<img src="https://github.com/pacstall/pacstall-programs/assets/104327997/00a078f3-526b-48f1-b4ce-30499cd01123" alt="You gotta play by the rules" width="200"/>

2024-09-10 11:22 UTC, vigress8 commented
Build fails because apx's Makefile uses `sudo`, which is bad practice and not supported by Pacstall.
For a quick fix, please patch the Makefile like this in `prepare()`
```bash
sed -i 's/sudo //' Makefile
```

2024-09-11 14:43 UTC, kbdharun commented
Hi, We have merged the Makefile PR upstream, can someone retrigger the failing jobs?

2024-09-11 16:33 UTC, vigress8 commented
I retriggered them, but there's now an error I don't understand on `debian:stable`
https://github.com/pacstall/pacstall-programs/actions/runs/10736150513/job/29971996728?pr=6394#step:11:867
Gonna take a guess this is due to the outdated Golang?

2024-09-11 16:36 UTC, vigress8 commented
Nevermind, you've indeed specified Go 1.22 in `go.mod`

2024-09-12 13:51 UTC, souhaiebtar commented
> Fix the title to conform to our standards, as explained in [our docs](https://github.com/pacstall/pacstall/wiki/101.5-Maintaining-a-Package#updating-your-package). You can also look at [past PRs](https://github.com/pacstall/pacstall-programs/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+label%3A%22Update+Package%22) to get an idea of how to format the title if you're unsure.
> 
> <img alt="You gotta play by the rules" width="200" src="https://private-user-images.githubusercontent.com/104327997/337923925-00a078f3-526b-48f1-b4ce-30499cd01123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNDkwNDMsIm5iZiI6MTcyNjE0ODc0MywicGF0aCI6Ii8xMDQzMjc5OTcvMzM3OTIzOTI1LTAwYTA3OGYzLTUyNmItNDhmMS1iNGNlLTMwNDk5Y2QwMTEyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxMzQ1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGU5NjFhODBjY2M5ZTFiYzJmNDk3NjYyODljMWI5YTUwODdmYmZhZWQ4MzlmNTIwNzQ5NWY4YWE1ODhjNjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bbMoHy-jDZ1bkWoPHGnihk2lfZKwIAr9JckximRoPuI">

my mistake, i will try to read the documentation and i will do as you asked

2024-09-12 14:16 UTC, vigress8 commented
Sorry, I assumed you were inactive, and I edited the pacscript to use Golang 1.22
The `sudo` patch is not necessary anymore since I submitted a PR upstream that fixed the issue, so you can remove that line

2024-09-12 14:16 UTC, souhaiebtar commented
> Sorry, I assumed you were inactive, and I edited the pacscript to use Golang 1.22 The `sudo` patch is not necessary anymore since I submitted a PR upstream that fixed the issue, so you can remove that line

ok my mistake, i will remove the line with `sudo`

2024-09-12 14:20 UTC, vigress8 requested changes
Add
```bash
export PATH=/usr/lib/go-1.22/bin:${PATH}
```
To `prepare()`, since Go 1.22 is not in PATH by default

2024-09-12 14:20 UTC, vigress8 commented on packages/apx-git/apx-git.pacscript
> +makedepends=("golang-1.22")
```suggestion
makedepends=("golang-1.22-go")
```
To avoid installing unnecessary parts of the Golang toolchain

2024-09-12 14:22 UTC, souhaiebtar commented
> Add
> 
> ```shell
> export PATH=/usr/lib/go-1.22/bin:${PATH}
> ```
> 
> To `prepare()`, since Go 1.22 is not in PATH by default

do i still need to add this line ?

2024-09-12 14:24 UTC, vigress8 commented
Yes

2024-09-12 14:35 UTC, souhaiebtar commented
> > Add
> > ```shell
> > export PATH=/usr/lib/go-1.22/bin:${PATH}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To `prepare()`, since Go 1.22 is not in PATH by default
> 
> do i still need to add this line ?

it's still reporting that `go not found`, do you have an idea how to resolve ?

2024-09-12 14:38 UTC, vigress8 commented
It's my mistake. That export should be done in `build()`, right before calling `make`

2024-09-12 14:41 UTC, souhaiebtar commented
> It's my mistake. That export should be done in `build()`, right before calling `make`

thank you, i think it's more my mistake than yours, i wanted to help but it ended up by you @vigress8 doing all the work

2024-09-12 14:48 UTC, vigress8 approved these changes

2024-09-12 14:50 UTC, merged

2024-09-12 15:06 UTC, Elsie19 commented
@souhaiebtar can you please make a PR that adds the line `incompatible=("*:bookworm")`. We forgot that before this was merged.