add: `mesa-kisak-fresh`
pacstall/pacstall-programs pull request #6403
Opened 2024-09-09 12:56 UTC by Xdavius

2024-09-11 10:20 UTC, Xdavius commented
need version constraint to provides

2024-09-13 13:05 UTC, vigress8 approved these changes

2024-10-23 20:37 UTC, Xdavius commented
Still the pinning problem who is blocking meson ...

2024-12-08 03:56 UTC, Elsie19 requested changes

2024-12-08 03:56 UTC, Elsie19 commented on packages/mesa-kisak-fresh/mesa-kisak-fresh.pacscript
> +
```suggestion
```

2024-12-08 03:57 UTC, Elsie19 approved these changes
LGTM. @oklopfer or @vigress8 could one of you review this as well because it's a fairly large PR?

2024-12-08 15:15 UTC, oklopfer approved these changes

2024-12-08 18:42 UTC, merged