add: `p3x-onenote-app`
pacstall/pacstall-programs pull request #6532
Opened 2024-10-13 15:46 UTC by harrietobrien

## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [ ] Contact devs
- [ ] Add maintainer to pacscript

2024-10-14 07:58 UTC, vigress8 requested changes

2024-10-14 07:58 UTC, vigress8 commented on packages/p3x-onenote-app/p3x-onenote-app.pacscript
> +depends=()
```suggestion
```
AppImages aren't auto-extracted anyway

2024-10-14 07:58 UTC, vigress8 commented on packages/p3x-onenote-app/p3x-onenote-app.pacscript
> +  chmod +x "${_name}-${pkgver}.AppImage"
```suggestion
```
Redundant lines

2024-10-14 13:29 UTC, harrietobrien commented on packages/p3x-onenote-app/onenote-svg.html
I can add link to sources and install that way later (at work rn)

2024-10-14 13:37 UTC, vigress8 commented on packages/p3x-onenote-app/onenote-svg.html
No, I meant - why is the file called `onenote-svg.html` is it's an svg? Why not call it `onenote.svg`

2024-10-17 14:08 UTC, Elsie19 submitted a review, later dismissed

2024-10-17 14:08 UTC, Elsie19 commented on packages/p3x-onenote-app/onenote.svg
> +<svg version="1.1" id="Livello_1" xmlns:x="http://ns.adobe.com/Extensibility/1.0/" xmlns:i="http://ns.adobe.com/AdobeIllustrator/10.0/" xmlns:graph="http://ns.adobe.com/Graphs/1.0/" xmlns="http://www
Can you move this file elsewhere. I know it's an SVG but I don't like adding images to the repo.

2024-10-27 14:17 UTC, vigress8 commented on packages/p3x-onenote-app/p3x-onenote-app.pacscript
> +)
```suggestion
)
incompatible=('debian:sid')
```

2024-10-27 14:31 UTC, vigress8 approved these changes

2024-10-27 14:31 UTC, merged