add: `gpu-screen-recorder`
pacstall/pacstall-programs pull request #6545
Opened 2024-10-16 12:30 UTC by bibelin

## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [ ] Contact devs
- [x] Add maintainer to pacscript

For build instructions and dependencies I looked at [gpu-screen-recorder-git AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gpu-screen-recorder-git), but for `source` I use a link to release tarball that can be found in [gpu-screen-recorder-gtk flatpak manifest](https://github.com/flathub/com.dec05eba.gpu_screen_recorder/blob/master/com.dec05eba.gpu_screen_recorder.yml#L41) (v4.2.2 wasn't uploaded to flathub yet at the time of writing this message, but there's an open PR for it).

2024-10-16 13:25 UTC, Elsie19 requested changes

2024-10-16 13:25 UTC, Elsie19 commented on packages/gpu-screen-recorder/gpu-screen-recorder.pacscript
> +repology="project:gpu-screen-recorder"
```suggestion
repology=("project:gpu-screen-recorder")
```

2024-10-16 13:25 UTC, Elsie19 commented on packages/gpu-screen-recorder/gpu-screen-recorder.pacscript
> +url="https://git.dec05eba.com/gpu-screen-recorder/about"
```suggestion
url='https://git.dec05eba.com/gpu-screen-recorder/about'
```

2024-10-16 17:21 UTC, bibelin commented
@dec05eba, glad to see you here and thanks for the hints! :)

As now you are aware of the pacstall package, I have a few questions for you:
* Would you like to maintain the pacscript (similar to a PKGBUILD) yourself?
* Could you include a section in your documentation showing Pacstall as a valid method of installation for `gpu-screen-recorder` for Debian/Ubuntu users?
* Would you be interested in adding `gpu-screen-recorder-gtk` to pacstall repository as well? Tbh I don't use it myself, but I don't mind adding and maintaining a pacscript.

2024-10-16 17:51 UTC, dec05eba commented
@bibelin 

>Would you like to maintain the pacscript (similar to a PKGBUILD) yourself?

>Would you be interested in adding gpu-screen-recorder-gtk to pacstall repository as well? Tbh I don't use it myself, but I don't mind adding and maintaining a pacscript.

I dont use debian/ubuntu so sorry no, I cant do that
>Could you include a section in your documentation showing Pacstall as a valid method of installation for gpu-screen-recorder for Debian/Ubuntu users?

Sure I'll do that when this is merged. There are some other distros that have packages as well so I'll add those as well there.

2024-10-20 18:00 UTC, vigress8 submitted a review, later dismissed

2024-10-21 04:51 UTC, vigress8 commented on packages/gpu-screen-recorder/gpu-screen-recorder.pacscript
> +repology=("project:gpu-screen-recorder")
```suggestion
repology=("project: gpu-screen-recorder")
```
Tooling expects a space here

2024-10-21 09:29 UTC, vigress8 approved these changes

2024-10-24 00:14 UTC, bibelin commented
@Elsie19 could you please review this again and merge if everything is okay?

2024-10-24 20:56 UTC, Elsie19 approved these changes

2024-10-24 20:56 UTC, merged