add: asdf-vm
pacstall/pacstall-programs pull request #6631
Opened 2024-11-13 14:06 UTC by niontrix

Add asdf version manager package.
For reference see https://asdf-vm.com

## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [ ] Contact devs
- [ ] Add maintainer to pacscript

2024-11-15 08:59 UTC, niontrix commented on packages/asdf-vm/asdf-vm.pacscript
> +  cp version.txt "${dst}"
Done. Thanks for the feedback!

2024-11-20 12:45 UTC, vigress8 submitted a review, later dismissed

2024-11-22 19:28 UTC, Elsie19 requested changes

2024-11-22 19:28 UTC, Elsie19 commented on packages/asdf-vm/asdf-vm.pacscript
> +pkgrel=1
```suggestion
pkgname="asdf-vm"
pkgver="0.14.1"
```

2024-11-25 17:27 UTC, Elsie19 requested changes
Can you put the repology key in here?

2024-11-26 16:43 UTC, niontrix commented
@Elsie19  unfortunately I get the error messages `Cannot find repology` when trying to `pacup -r asdf-vm.pacscript`. Do you have any hints what the problem might be?

2024-11-26 17:18 UTC, vigress8 commented
That's not what `-r` does - it prints the Repology API response using the existing metadata from the `repology` variable.
Add `repology=("project: ${gives}") to the pacscript

2024-11-27 12:22 UTC, niontrix commented
Sorry, I have trouble understanding the process.
At the moment there is no `gives` variable in my pacscript. Do I need to add it with `gives="asdf"`?
Also, do you mean I should not run `pacup -r asdf-vm.pacscript`? If so, why not? I thought this would show me that it is able to find a package that pacup could then use to update the version and other information for a next release, does it not?

2024-11-27 13:17 UTC, niontrix commented
But how do I know that it works like it should? That's why I wanted to see the output of `pacup --show-repology`.

2024-11-27 16:26 UTC, vigress8 commented on packages/asdf-vm/asdf-vm.pacscript
> +repology=("project: ${pkgname})
```suggestion
repology=("project: ${pkgname}")
```

2024-11-27 16:34 UTC, vigress8 approved these changes

2024-11-29 22:21 UTC, niontrix commented
@Elsie19 is there still something missing or something I need to do?

2024-11-29 22:26 UTC, Elsie19 approved these changes

2024-11-29 22:27 UTC, merged