add: `cortile`
pacstall/pacstall-programs pull request #6698
Opened 2024-11-23 18:14 UTC by ajstrongdev

Add cortile pacscript with custom build configuration to disable auto-update using `main.flags=disable-dbus-interface,disable-release-info`

2024-11-23 19:13 UTC, oklopfer commented on packages/cortile/cortile.pacscript
> +makedepends=("golang")
```suggestion
makedepends=("golang" "golang-1.23")
```

2024-11-24 23:42 UTC, Elsie19 commented
Look at the precommit.ci action failure.

2024-12-08 03:58 UTC, Elsie19 requested changes

2024-12-08 03:58 UTC, Elsie19 commented on packages/cortile/cortile.pacscript
> +  install -Dm755 "$pkgname" "${pkgdir}/usr/bin/${pkgname}"
```suggestion
  install -Dm755 "${pkgname}" "${pkgdir}/usr/bin/${pkgname}"
```

2024-12-11 23:29 UTC, Elsie19 approved these changes

2024-12-11 23:29 UTC, merged