feat: add exiftool package
pacstall/pacstall-programs pull request #6700
Opened 2024-11-23 21:01 UTC by md5-ishaque

Add ExifTool package to Pacstall repository

ExifTool is a platform-independent Perl library and command-line tool for reading, writing, and editing metadata in a wide variety of files. This PR adds:
- exiftool.pacscript: Package script for version 13.03
- .SRCINFO: Package metadata file

Features:
- Installs the latest stable version (13.03)
- Includes documentation files
- Properly handles dependencies (perl)
- Uses standard build process with perl's Makefile.PL

Testing:
- Package builds and installs successfully
- Binary runs correctly after installation

2024-11-26 17:23 UTC, vigress8 requested changes

2024-11-26 17:23 UTC, vigress8 commented on packages/exiftool/exiftool.pacscript
> +pkgrel="1"
```suggestion
```
Redundant

2024-11-26 17:23 UTC, vigress8 commented on packages/exiftool/exiftool.pacscript
> +name="exiftool"
```suggestion
```
This variable is not used anymore

2024-11-26 17:23 UTC, vigress8 commented on packages/exiftool/exiftool.pacscript
> +maintainer="Ishaque <muhammadishaque812@gmail.com>"
```suggestion
maintainer=("Ishaque <muhammadishaque812@gmail.com>")
```
`maintainer` is an array

2024-11-26 17:23 UTC, vigress8 commented on packages/exiftool/exiftool.pacscript
> +license="GPL-2.0-or-later"
```suggestion
license=("GPL-2.0-or-later")
```
`license` is an array

2024-11-26 17:23 UTC, vigress8 commented on packages/exiftool/exiftool.pacscript
> +
```suggestion
```
Redundant

2024-11-26 17:23 UTC, vigress8 commented on packages/exiftool/exiftool.pacscript
> +  install -Dm644 Changes "${pkgdir}/usr/share/doc/${name}/Changes"
```suggestion
  install -Dm644 README Changes -t "${pkgdir}/usr/share/doc/${pkgname}"
```

2024-11-26 17:26 UTC, vigress8 commented on packages/exiftool/exiftool.pacscript
> +pkgdesc="A platform-independent Perl library for reading and writing EXIF data"
```suggestion
pkgdesc="Platform-independent Perl library for reading and writing EXIF data"
```

2024-11-28 13:54 UTC, vigress8 commented
Please enable "Allow edits by maintainers", otherwise the pre-commit CI bot can't do its job

2024-11-28 14:37 UTC, crypt0-wizard commented
> Please enable "Allow edits by maintainers", otherwise the pre-commit CI bot can't do its job

2024-11-28 14:38 UTC, crypt0-wizard commented
> > Please enable "Allow edits by maintainers", otherwise the pre-commit CI bot can't do its job

Done

2024-11-30 09:26 UTC, vigress8 approved these changes

2024-12-06 14:47 UTC, Elsie19 requested changes

2024-12-06 14:47 UTC, Elsie19 commented on packages/exiftool/exiftool.pacscript
> +url="https://exiftool.org"
```suggestion
url='https://exiftool.org'
```

2024-12-06 14:47 UTC, Elsie19 commented on packages/exiftool/exiftool.pacscript
> +repology=("project: ${gives}")
```suggestion
repology=("project: ${pkgname}")
```

2024-12-08 03:54 UTC, Elsie19 requested changes

2024-12-08 03:54 UTC, Elsie19 commented on packages/exiftool/exiftool.pacscript
> +  make
```suggestion
  make -j"${NCPU}"
```

2024-12-09 07:03 UTC, vigress8 submitted a review, later dismissed

2024-12-10 16:10 UTC, Elsie19 requested changes

2024-12-10 16:10 UTC, Elsie19 commented on packages/exiftool/exiftool.pacscript
> +
```suggestion
```

2024-12-12 03:39 UTC, Elsie19 approved these changes

2024-12-12 03:39 UTC, merged