fix(tenacity-git): upd pacscript to new version
pacstall/pacstall-programs pull request #6732
Opened 2024-12-07 13:54 UTC by Xdavius

2024-12-08 00:56 UTC, Elsie19 requested changes
This isn't what "fix" is for.

2024-12-11 14:52 UTC, Elsie19 commented
Any package update can include fixes and don't have to be labeled as a fix. So you should change the title to an `upd` one.

2024-12-11 14:53 UTC, Elsie19 requested changes

2024-12-11 14:53 UTC, Elsie19 commented on packages/tenacity-git/tenacity-git.pacscript
> +
```suggestion
```

2024-12-11 14:53 UTC, Elsie19 commented on packages/tenacity-git/tenacity-git.pacscript
> +    test -f tenacity.png && mv tenacity.png apps
```suggestion
    [[ -f tenacity.png ]] && mv tenacity.png apps
```

2024-12-11 14:53 UTC, Elsie19 commented on packages/tenacity-git/tenacity-git.pacscript
> +  make -j"$(NCPU)" .
```suggestion
  make -j"${NCPU}" .
```

2024-12-11 14:53 UTC, Elsie19 commented on packages/tenacity-git/tenacity-git.pacscript
> +  test -f "${pkgdir}/usr/tenacity" && rm "${pkgdir}/usr/tenacity" # remove unused launch script
```suggestion
  [[ -f "${pkgdir}/usr/tenacity" ]] && rm "${pkgdir}/usr/tenacity" # remove unused launch script
```

2024-12-21 21:32 UTC, oklopfer requested changes

2024-12-21 21:32 UTC, oklopfer commented on packages/tenacity-git/tenacity-git.pacscript
> +fi
```suggestion
depends=("libc6" "libexpat1" "libgcc-s1" "libgdk-pixbuf-2.0-0" "libglib2.0-0" "libgtk-3-0" "libid3tag0" "liblilv-0-0" "libmad0" "libogg0" "libportaudio2" "libsndfile1" "libsoundtouch1" "libsoxr0" "libstdc++6" "libsuil-0-0" "libtwolame0" "libvamp-hostsdk3v5" "libvorbis0a" "libvorbisenc2" "libvorbisfile3" "libportmidi0" "libzip4" "libjsoncpp25" "libavcodec-dev" "libavformat-dev" "libavutil-dev" "libflac++10" "libflac12" "libportsmf-dev" "libwxbase3.2-1" "libwxgtk3.2-1")
```

2025-01-02 20:30 UTC, Elsie19 requested changes

2025-01-02 20:30 UTC, Elsie19 commented on packages/tenacity-git/tenacity-git.pacscript
```suggestion

```

2025-01-08 14:58 UTC, Elsie19 approved these changes

2025-01-09 03:58 UTC, merged