add: `cbindgen`
pacstall/pacstall-programs pull request #6757
Opened 2024-12-13 16:22 UTC by Xdavius

2024-12-15 07:57 UTC, vigress8 commented on packages/cbindgen/cbindgen.pacscript
> +url="https://github.com/mozilla/cbindgen"
```suggestion
url="https://github.com/mozilla/cbindgen"
repology=("project: ${gives}")
maintainer=("xdavius <xdavius@github.com>")
```

2024-12-18 14:20 UTC, Elsie19 requested changes

2024-12-18 14:20 UTC, Elsie19 commented on packages/cbindgen/cbindgen.pacscript
> +url="https://github.com/mozilla/cbindgen"
```suggestion
url='https://github.com/mozilla/cbindgen'
```

2024-12-18 14:20 UTC, Elsie19 commented on packages/cbindgen/cbindgen.pacscript
> +license=(MPL-2.0)
```suggestion
license=("MPL-2.0")
```

2024-12-18 14:20 UTC, Elsie19 commented on packages/cbindgen/cbindgen.pacscript
> +)
```suggestion
depends=("libglib2.0-dev")
makedepends=("libglib2.0-dev" "git")
```

2024-12-18 14:20 UTC, Elsie19 commented on packages/cbindgen/cbindgen.pacscript
> +  cargo build --release
```suggestion
  CARGO_PROFILE_RELEASE_DEBUG=2 \
    CARGO_PROFILE_RELEASE_LTO=true \
    CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1 \
    cargo build --release
```

2024-12-18 17:04 UTC, Elsie19 requested changes

2024-12-18 17:04 UTC, Elsie19 commented on packages/cbindgen/cbindgen.pacscript
> +pkgrel=1
```suggestion
```

This is implicit.

2024-12-18 17:04 UTC, Elsie19 commented on packages/cbindgen/cbindgen.pacscript
> +source=("git+${url}#tag=v${pkgver}")
Use the full url here. Do not interpolate `${url}`.

2024-12-21 14:40 UTC, Elsie19 requested changes

2024-12-21 14:40 UTC, Elsie19 commented on packages/cbindgen/cbindgen.pacscript
> +pkgver=0.27.0
```suggestion
pkgname="cbindgen"
pkgver="0.27.0"
```

2024-12-21 14:40 UTC, Elsie19 commented on packages/cbindgen/cbindgen.pacscript
> +repology=("project: ${gives}")
```suggestion
repology=("project: ${pkgname}")
```

2025-01-10 07:32 UTC, oklopfer approved these changes

2025-01-10 07:32 UTC, merged