add: `python3-editables`
pacstall/pacstall-programs pull request #6761
Opened 2024-12-17 15:28 UTC by Xdavius

2024-12-21 14:46 UTC, Elsie19 requested changes

2024-12-21 14:46 UTC, Elsie19 commented on packages/python3-editables/python3-editables.pacscript
> +pkgrel=5
```suggestion
pkgname="python3-editables"
pkgver="0.5"
```

2024-12-21 14:46 UTC, Elsie19 commented on packages/python3-editables/python3-editables.pacscript
> +  install -d "${pkgdir}/usr/share/licenses/${_pkgname}"
This isn't defined.

2024-12-21 14:46 UTC, Elsie19 commented on packages/python3-editables/python3-editables.pacscript
> +  local site_packages=$(python3 -c "import site; print(site.getsitepackages()[0])")
```suggestion
  local site_packages="$(python3 -c "import site; print(site.getsitepackages()[0])")"
```

2024-12-21 14:46 UTC, Elsie19 commented on packages/python3-editables/python3-editables.pacscript
> +source=("${pkgname}::git+${url}#commit=${_commit}")
Add full URL instead of `${url}`.

2025-01-10 07:45 UTC, oklopfer approved these changes

2025-01-10 07:45 UTC, merged