add: 'ufetch-debian'
pacstall/pacstall-programs pull request #6801
Opened 2024-12-29 16:25 UTC by vlprokopenko

Added the debian version of ufetch

2024-12-29 20:45 UTC, Elsie19 approved these changes

2024-12-29 20:47 UTC, Elsie19 requested changes

2024-12-29 20:47 UTC, Elsie19 commented on packages/ufetch-debian/ufetch-debian.pacscript
> +source=("https://gitlab.com/jschx/ufetch/-/raw/main/ufetch-debian")
```suggestion
source=("https://gitlab.com/jschx/ufetch/-/raw/v${pkgver}/ufetch-debian")
```

And add a sha-sum also.

2024-12-29 20:57 UTC, vlprokopenko commented
there is no sha sum for it by the way.

2024-12-30 23:33 UTC, Elsie19 commented
Download the file, run `sha256sum ufetch-debian`, get the first part. That's your sha sum.

2025-01-05 21:03 UTC, vlprokopenko commented
yes, but there's no need for a sha sum. It's literally one file from gitlab. Sorry for the delay in response by the way.

2025-01-05 21:05 UTC, Elsie19 requested changes

2025-01-05 21:05 UTC, Elsie19 commented on packages/ufetch-debian/ufetch-debian.pacscript
> +source=("https://gitlab.com/jschx/ufetch/-/raw/v${pkgver}/ufetch-debian")
```suggestion
source=("https://gitlab.com/jschx/ufetch/-/raw/v${pkgver}/ufetch-debian")
sha256sums=("8bddd627952d965f6fc11010dd227c8bc3c7856df672db1e738e7e8f4f2d6a87")
```

2025-01-07 13:22 UTC, Elsie19 approved these changes

2025-01-07 13:22 UTC, merged