[Package Add] freetube-bin
pacstall/pacstall-programs pull request #71
Opened 2021-07-18 23:14 UTC by WRM-42

2021-07-19 04:41 UTC, wizard-28 commented
Shouldn't it be `freetube-deb`?

2021-07-19 11:21 UTC, Henryws requested changes
yeah, what @wizard-28 said

2021-07-19 13:57 UTC, wizard-28 requested changes
I think it also needs to have a `gives` field, for it to work.

See [this comment](https://github.com/pacstall/pacstall-programs/pull/69/files#r671796341) by @NarutoXY.

And @NarutoXY it will be helpful if you add the `deb` pacscript making instructions to [`make-a-pacscript.md`](https://github.com/pacstall/pacstall-programs/blob/master/make-a-pacscript.md)

2021-07-19 14:07 UTC, Henryws commented
> I think it also needs to have a `gives` field, for it to work.
> 
> See [this comment](https://github.com/pacstall/pacstall-programs/pull/69/files#r671796341) by @NarutoXY.
> 
> And @NarutoXY it will be helpful if you add the `deb` pacscript making instructions to [`make-a-pacscript.md`](https://github.com/pacstall/pacstall-programs/blob/master/make-a-pacscript.md)

Why would we need a `gives` field? Would we hook into apt somehow?

2021-07-20 03:50 UTC, wizard-28 commented
> Why would we need a gives field? Would we hook into apt somehow?

See @NarutoXY's comment, I think he is the one who added `.deb` support so, he should know the best.

2021-07-20 03:53 UTC, NarutoXY commented
Hey we are currently using give field for removing package as in my mind it's always the name by which apt installs any deb package and to remove it we need that name. We can use apt list then search then what not but it'll be complicated. Never work and it will also be culprit of deleting wrong program.

2021-07-20 10:37 UTC, NarutoXY commented on packages/freetube-deb/freetube-deb.pacscript
> +url="https://github.com/FreeTubeApp/FreeTube/releases/download/v${version}-beta/freetube_${version}_amd64.deb"
Add ```gives=freetube```

2021-07-21 02:11 UTC, NarutoXY approved these changes

2021-07-21 10:43 UTC, wizard-28 approved these changes

2021-07-23 17:31 UTC, merged