Update `opensnitch-ui-deb`
pacstall/pacstall-programs pull request #728
Opened 2022-02-11 15:22 UTC by echometerain

2022-02-16 11:49 UTC, wizard-28 commented
@echometerain

2022-02-17 14:11 UTC, Henryws approved these changes

2022-02-17 14:15 UTC, wizard-28 requested changes
Run the pre-commit hooks

2022-02-17 15:43 UTC, wizard-28 approved these changes

2022-02-17 15:43 UTC, merged