upd(micro): `2.0.8` -> `2.0.10`
pacstall/pacstall-programs pull request #744
Opened 2022-02-12 22:05 UTC by cat-master21

2022-02-12 23:13 UTC, Henryws requested changes

2022-02-12 23:13 UTC, Henryws commented on packages/micro/micro.pacscript
> +    sudo cp micro "/usr/src/pacstall/micro/usr/bin"
```suggestion
    sudo install -Dm644 micro "/usr/src/pacstall/micro/usr/bin/micro"
```

2022-02-12 23:13 UTC, Henryws commented on packages/micro/micro.pacscript
> +    sudo cp "micro.desktop" "/usr/src/pacstall/micro/usr/share/applications"
```suggestion
    sudo install -Dm644 micro.desktop "/usr/src/pacstall/micro/usr/share/applications/micro.desktop"
```

2022-02-12 23:13 UTC, Henryws commented on packages/micro/micro.pacscript
> +    sudo cp micro.1.tar.gz "/usr/src/pacstall/micro/usr/share/man/man1"
```suggestion
    sudo install -Dm644 micro.1.tar.gz "/usr/src/pacstall/micro/usr/share/man/man1/micro.1.tar.gz"
```

2022-02-12 23:43 UTC, Henryws requested changes
Remove this line, because it is useless now that `install` commands are used

2022-02-12 23:43 UTC, Henryws commented on packages/micro/micro.pacscript
> +    sudo mkdir -p "/usr/src/pacstall/micro/usr/bin" "/usr/src/pacstall/micro/usr/share/man/man1" "/usr/src/pacstall/micro/usr/share/applications"
```suggestion

```

2022-02-12 23:54 UTC, Henryws approved these changes

2022-02-12 23:57 UTC, Henryws requested changes
Oops forgot to chmod it

2022-02-12 23:57 UTC, Henryws commented on packages/micro/micro.pacscript
> +    sudo install -Dm644 micro.desktop "/usr/src/pacstall/micro/usr/share/applications/micro.desktop"
```suggestion
    sudo install -Dm644 micro.desktop "/usr/src/pacstall/micro/usr/share/applications/micro.desktop"
    sudo chmod +x "/usr/src/pacstall/micro/usr/bin/micro"
```

2022-02-13 01:00 UTC, Henryws approved these changes

2022-02-13 01:00 UTC, merged

2022-02-13 02:32 UTC, wizard-28 commented
@cat-master21 Would you like to make yourself the maintainer of this package?

@edward-riley Are you okay with transferring the responsibility to @cat-master21?