upd(smartgit): `21.1.0` -> `21.2.2`
pacstall/pacstall-programs pull request #745
Opened 2022-02-12 22:31 UTC by cat-master21

2022-02-12 23:03 UTC, Henryws requested changes

2022-02-12 23:03 UTC, Henryws commented on packages/smartgit/smartgit.pacscript
>  version="21.1.0"
update `version`

2022-02-12 23:07 UTC, Henryws approved these changes

2022-02-12 23:07 UTC, merged

2022-02-13 02:53 UTC, wizard-28 commented
@echometerain do you wish to continue maintaining this pacscript?