rm: `amdgpu-dkms-firmware-deb`
pacstall/pacstall-programs pull request #752
Opened 2022-02-15 01:25 UTC by cat-master21

Remove amdgpu-dkms-firmware-deb as a thought amdgpu-dkms was a dependency for aomp-deb. The issue I had however was not that but an issue with aomp itself. The CI may fail to install as https://raw.githubusercontent.com/pacstall/pacstall-programs/master/packages/aomp-deb/fix_AOMP.patch is not merged yet.

2022-02-15 01:30 UTC, Henryws requested changes

2022-02-15 01:30 UTC, Henryws commented on packages/aomp-deb/aomp-deb.pacscript
> +patch="https://raw.githubusercontent.com/pacstall/pacstall-programs/master/packages/aomp-deb/fix_AOMP.patch"
Patch is an array

2022-02-16 02:46 UTC, cat-master21 commented
Should be ready. Note that pre-commit.ci should fail as it messes with my patch file.

2022-02-16 03:00 UTC, Henryws requested changes
Redirect the tee output to `/dev/null` to prevent terminal output

2022-02-16 03:00 UTC, Henryws commented on packages/aomp-deb/aomp-deb.pacscript
> +patch | sudo tee "/usr/lib/aomp/bin/mymcpu" < "./PACSTALL_patchesdir/fix_AOMP.patch"
```suggestion
patch | sudo tee "/usr/lib/aomp/bin/mymcpu" < "./PACSTALL_patchesdir/fix_AOMP.patch" >/dev/null
```

2022-02-18 00:44 UTC, cat-master21 commented
Done @Henryws

2022-02-18 00:57 UTC, Henryws requested changes

2022-02-18 00:57 UTC, Henryws commented on packages/aomp-deb/aomp-deb.pacscript
> +patch | sudo tee "/usr/lib/aomp/bin/mymcpu" < "./PACSTALL_patchesdir/fix_AOMP.patch" > /dev/null
```suggestion
sudo patch | tee "/usr/lib/aomp/bin/mymcpu" < "./PACSTALL_patchesdir/fix_AOMP.patch" > /dev/null
```

2022-02-19 13:56 UTC, wizard-28 commented
@Henryws continue your review.

2022-02-22 02:06 UTC, Henryws requested changes
Styling issues

2022-02-22 02:06 UTC, Henryws commented on packages/aomp-deb/aomp-deb.pacscript
> +sudo patch | tee "/usr/lib/aomp/bin/mymcpu" < "./PACSTALL_patchesdir/fix_AOMP.patch" > /dev/null
```suggestion
	# patch to fix AOMP variable.
	sudo patch | tee "/usr/lib/aomp/bin/mymcpu" < "./PACSTALL_patchesdir/fix_AOMP.patch" > /dev/null
```

2022-02-23 01:26 UTC, Henryws requested changes
https://github.com/pacstall/pacstall-programs/runs/5297309951?check_suite_focus=true#step:9:79

2022-02-23 01:42 UTC, cat-master21 commented
This may be because the file: https://raw.githubusercontent.com/pacstall/pacstall-programs/master/packages/aomp-deb/fix_AOMP.patch does not exist.

2022-02-23 01:44 UTC, Henryws approved these changes

2022-02-23 10:01 UTC, merged