add: PULL_REQUEST_TEMPLATE
pacstall/pacstall-programs pull request #754
Opened 2022-02-16 03:26 UTC by cat-master21

This seems to be a bit overdue.

2022-02-16 03:35 UTC, cat-master21 commented
Maybe I should change this to a txt file as Codacy seems not to link markdown file.

2022-02-16 10:02 UTC, wizard-28 requested changes

2022-02-16 22:25 UTC, cat-master21 commented
I'm not sure if it's possible to self-assign on github's templates but I added wizard-28.

2022-02-19 07:46 UTC, wizard-28 approved these changes
Well, let's try it and see what happens

2022-02-19 07:47 UTC, merged