add: `yafetch-git`
pacstall/pacstall-programs pull request #764
Opened 2022-02-18 01:57 UTC by Henryws

## Progress 

- [x] Edit packagelist
- [x] Add initial pacscript
- [x] Add maintainer to pacscript

2022-02-18 14:23 UTC, volitank submitted a review, later dismissed

2022-02-19 07:44 UTC, wizard-28 requested changes
Aren't you going to contact the devs?

2022-02-19 07:44 UTC, wizard-28 commented on packages/yafetch-git/yafetch-git.pacscript
> +breaks="${gives}-deb ${gives}-bin ${gives}-app"
```suggestion
breaks="${gives}-deb ${gives}-bin ${gives}-app ${gives}-git"
```

2022-02-19 07:44 UTC, wizard-28 commented on packages/yafetch-git/yafetch-git.pacscript
> +  sudo install -Dm755 yafetch "/usr/src/pacstall/yafetch-git/usr/bin/yafetch"
Use `STOWDIR`

2022-02-19 13:12 UTC, Henryws commented
> Aren't you going to contact the devs?

I am the dev!

2022-02-19 13:16 UTC, volitank commented
Should we even include this? I heard there was a better python version coming soon.

2022-02-19 13:17 UTC, Henryws commented
> Should we even include this? I heard there was a better python version coming soon.

I can open a separate PR for `yapfetch`

2022-02-19 13:17 UTC, wizard-28 commented
> > Aren't you going to contact the devs?
> 
> I am the dev!

Have you tried contacting yourself?

2022-02-19 13:53 UTC, wizard-28 approved these changes

2022-02-19 13:54 UTC, wizard-28 requested changes
Check CI logs: https://github.com/pacstall/pacstall-programs/runs/5258913812?check_suite_focus=true

2022-02-19 14:31 UTC, volitank approved these changes

2022-02-19 14:32 UTC, wizard-28 approved these changes

2022-02-19 14:32 UTC, merged