Update make-a-pacscript.md
pacstall/pacstall-programs pull request #77
Opened 2021-07-22 21:57 UTC by rain1598

replace pkgname with $name
add variable showcase

2021-07-23 07:48 UTC, wizard-28 commented
@rain1598 there has been an update to `contributing.md`. From the next PR, please follow that.

2021-07-27 21:33 UTC, D-Brox approved these changes

2021-07-29 17:18 UTC, wizard-28 requested changes
Fix Codacy errors

2021-07-29 17:34 UTC, wizard-28 approved these changes

2021-07-29 17:35 UTC, merged