upd(pipewire): `0.3.44` -> `0.3.47`
pacstall/pacstall-programs pull request #770
Opened 2022-02-20 00:41 UTC by Henryws

2022-02-20 00:46 UTC, Henryws commented
https://github.com/pacstall/pacstall-programs/runs/5261730506?check_suite_focus=true#step:9:1587

This issue can be fixed by removing apt's meson and installing it from pip. Although I remember this working fine in a VM a while back

2022-02-21 14:07 UTC, wizard-28 requested changes

2022-02-21 14:07 UTC, wizard-28 commented on packages/pipewire/pipewire.pacscript
> +            sudo apt remove meson
why not `purge`?

2022-02-22 10:49 UTC, wizard-28 commented
WTF happened with the CI.

2022-02-24 13:32 UTC, wizard-28 approved these changes

2022-02-24 13:33 UTC, wizard-28 commented
I guess since you've requested a review from @D-Brox I'll just enable auto squash for now.

2022-03-01 14:25 UTC, merged