upd(an-anime-game-launcher-bin): 2.1.5 -> 2.2.0
pacstall/pacstall-programs pull request #777
Opened 2022-02-22 16:40 UTC by Mar0xy

2022-02-23 13:17 UTC, wizard-28 commented
@Henryws doesn't work in Debian, so... what to do?

2022-02-23 13:58 UTC, wizard-28 requested changes

2022-02-23 13:58 UTC, wizard-28 commented on packages/an-anime-game-launcher-bin/an-anime-game-launcher-bin.pacscript
>  name=an-anime-game-launcher-bin
```suggestion
# Detect if the OS is Debian and error out
if [[ -f /etc/debian_version ]]; then
    fancy_message error "This script doesn't work on Debian"
    cleanup # Trigger pacstall cleanups
    exit 1
fi

name=an-anime-game-launcher-bin
```

Error out if the OS is detected as Debian.

We'll add a variable (or an array) in the future where you can specify what OSes the package doesn't work on. But for now you'll have to manually program it and error out.

2022-02-23 16:20 UTC, Mar0xy commented
Seems like that didn't work as it just stopped at "sourcing pacscript..." for all tests.

2022-02-24 15:17 UTC, Henryws requested changes

2022-02-24 15:17 UTC, Henryws commented on packages/an-anime-game-launcher-bin/an-anime-game-launcher-bin.pacscript
>  name=an-anime-game-launcher-bin
```suggestion
if [[ "$(lsb_release -si)" == "Debian" ]]; then
    fancy_message error "This script doesn't work on Debian"
    cleanup # Trigger pacstall cleanups
    exit 1
fi
name=an-anime-game-launcher-bin
```

2022-02-24 19:36 UTC, Mar0xy commented
That one seems to just be ignored due to lsb_release missing "Line 1: lsb_release: command not found"

2022-02-24 21:14 UTC, Henryws requested changes

2022-02-24 21:14 UTC, Henryws commented on packages/an-anime-game-launcher-bin/an-anime-game-launcher-bin.pacscript
> +fi
```suggestion
if [[ "$(grep -Po 'ID=\K[^"]+' /etc/os-release)" == "debian" ]]; then
    fancy_message error "This script doesn't work on Debian"
    cleanup # Trigger pacstall cleanups
    exit 1
fi
```

2022-02-26 12:52 UTC, wizard-28 commented
Linking this with https://github.com/pacstall/pacstall/pull/510, as the error messages aren't getting printed on Debian systems

2022-03-01 14:21 UTC, wizard-28 commented
> Linking this with [pacstall/pacstall#510](https://github.com/pacstall/pacstall/pull/510), as the error messages aren't getting printed on Debian systems

This has been merged in `develop`, and will be released soon, merging this PR meanwhile.

2022-03-01 14:22 UTC, wizard-28 approved these changes

2022-03-01 14:22 UTC, merged