Update brave-browser-nightly-deb to v1.38.5
pacstall/pacstall-programs pull request #789
Opened 2022-02-27 05:11 UTC by theblobscp

2022-02-27 07:09 UTC, wizard-28 requested changes
Hashes don't match

2022-02-27 09:56 UTC, wizard-28 commented
@Korkmatik do you wish to continue maintaining this script?

2022-02-27 20:23 UTC, Korkmatik commented
> @Korkmatik do you wish to continue maintaining this script?

Thanks for asking. Unfortunately currently I don't have time to maintain it.

2022-02-28 05:23 UTC, wizard-28 requested changes

2022-02-28 05:23 UTC, wizard-28 commented on packages/brave-browser-nightly-deb/brave-browser-nightly-deb.pacscript
> +hash="da93a1b5c7febb45686979927a4bc81e878bf144ee676c16e4e9d6f621e4a85f "
The hash is incorrect. The hash check fails in the CI.

2022-02-28 05:23 UTC, wizard-28 commented on packages/brave-browser-nightly-deb/brave-browser-nightly-deb.pacscript
>  maintainer="Korkmatik <9c54efc1-143b-4f5f-9d2f-f6f189583f0f@aleeas.com>"
Replace Korkmatik's details with yours @theblobscp . If you're willing to maintain it of course.

2022-03-03 15:54 UTC, wizard-28 requested changes
Apparently the hashes still don't match

2022-03-04 03:02 UTC, Henryws requested changes
Proper hash

2022-03-04 03:02 UTC, Henryws commented on packages/brave-browser-nightly-deb/brave-browser-nightly-deb.pacscript
> +hash="da93a1b5c7febb45686979927a4bc81e878bf144ee676c16e4e9d6f621e4a85f"
```suggestion
hash="002bc7729a53c69acbd2c1f52caa3e822d1fbc71a0c424b8f09be4b750ff3c74"
```

2022-03-04 03:11 UTC, Henryws approved these changes

2022-03-05 05:52 UTC, wizard-28 requested changes

2022-03-05 05:52 UTC, wizard-28 commented on packages/brave-browser-nightly-deb/brave-browser-nightly-deb.pacscript
>  breaks="${gives}-bin ${gives}-app"
```suggestion
breaks="${gives}-bin ${gives}-app ${gives}-git ${gives}"
```

2022-03-09 20:54 UTC, theblobscp commented
I'm not going to be able to mantain this, maybe some other time I might come back? But for now, this is 'stale'

2022-03-09 20:54 UTC, closed without merging

2022-03-09 22:09 UTC, Henryws commented
Hmmm, I might take up maintaining this as I currently use brave.