add `emby-server-deb`
pacstall/pacstall-programs pull request #793
Opened 2022-02-28 11:03 UTC by warofzen

Add a pacscript to install [Emby Server](https://github.com/MediaBrowser/Emby.Releases) from their .deb release

2022-02-28 14:23 UTC, wizard-28 requested changes
@Henryws I think it's okay to not contact the devs for this.

2022-02-28 14:23 UTC, wizard-28 commented on packages/emby-server-deb/emby-server-deb.pacscript
> +breaks="${gives} ${gives}-bin ${gives}-app"
```suggestion
breaks="${gives} ${gives}-bin ${gives}-app ${gives}-git"
```

2022-03-01 07:41 UTC, wizard-28 approved these changes

2022-03-01 07:41 UTC, wizard-28 commented
@warofzen the CI fails in all OSes

2022-03-01 12:43 UTC, warofzen commented
It seems that the CI cannot create a symlink for the `emby-server.service` file, but it worked just fine on my local machine:
https://asciinema.org/a/DwwakO0Zdpf6LiibqCtP1WniB

2022-03-01 14:26 UTC, wizard-28 commented
> It seems that the CI cannot create a symlink for the `emby-server.service` file, but it worked just fine on my local machine: https://asciinema.org/a/DwwakO0Zdpf6LiibqCtP1WniB

Okay, so @Henryws will test it on his machine, and then we can merge.

2022-03-02 23:22 UTC, merged