add: `bottles-v1-deb`
pacstall/pacstall-programs pull request #802
Opened 2022-03-03 00:06 UTC by cat-master21

2022-03-03 00:58 UTC, cat-master21 commented
Wine64 has issues apparently https://github.com/pacstall/pacstall-programs/runs/5400356628?check_suite_focus=true#step:9:46747.

2022-03-03 01:43 UTC, cat-master21 commented
Still as issues? https://github.com/pacstall/pacstall-programs/runs/5400751029?check_suite_focus=true#step:9:46444

2022-03-03 01:49 UTC, Henryws commented
> Still as issues? [pacstall/pacstall-programs/runs/5400751029?check_suite_focus=true#step:9:46444](https://github.com/pacstall/pacstall-programs/runs/5400751029?check_suite_focus=true#step:9:46444)

Yeah the issue is with the wine pacscript:
```diff
1,3c1,3
< name="wine"
< pkgname="wine"
< provides="wine-stable wine"
---
> name="wine64"
> pkgname="wine64"
> provides="wine64-stable wine64"
19c19
<           sudo make install DESTDIR=/usr/src/pacstall/wine
---
>           sudo make install DESTDIR=/usr/src/pacstall/wine64
```

Change the wine pacscript accordingly.

2022-03-05 05:50 UTC, wizard-28 commented
@Henryws I think you'll be able to do the review better on this one.

2022-03-07 01:52 UTC, Henryws commented
Does Bottles *need* the latest wine version? Because adding `wine64` as a pacdep will take insanely long building times.

2022-03-07 03:10 UTC, cat-master21 commented
This is why: https://github.com/pacstall/pacstall-programs/runs/5442664531?check_suite_focus=true#step:9:41 Debian doesn't have wine-stable unlike Ubuntu.

2022-03-10 08:17 UTC, wizard-28 commented
@Henryws any updates on this?

2022-03-10 22:51 UTC, Henryws commented
> @Henryws any updates on this?

Workin on it.

2022-03-11 22:27 UTC, Henryws requested changes
bottles doesn't call the wine64 pacdep

2022-03-12 17:54 UTC, cat-master21 commented
No, but it calls for `wine-stable` which is only on Ubuntu, not on Debian so Debian installation fails but wine64 as a pacdep should solve the issue.

2022-03-12 17:57 UTC, Henryws commented
> No, but it calls for `wine-stable` which is only on Ubuntu, not on Debian so Debian installation fails but wine64 as a pacdep should solve the issue.

Add an if statement checking if the OS is debian, and if so, make the pacdep, and if not, add `wine-stable` to `depends`

2022-03-20 06:16 UTC, wizard-28 commented
@Henryws any updates on this?

2022-03-20 14:19 UTC, Henryws commented
> @Henryws any updates on this?

Still waiting on https://github.com/pacstall/pacstall-programs/pull/802#issuecomment-1065930986

2022-03-20 16:13 UTC, cat-master21 commented
So I fixed this at Bottles at pull requests https://github.com/bottlesdevs/Bottles/pull/1204/files and https://github.com/bottlesdevs/Bottles/pull/1207/files to switch to GitHub actions and use `wine` instead of `wine-stable`.

2022-03-20 16:14 UTC, cat-master21 commented
The error is from trying to install Bottles-v1 and wine64.

2022-03-20 21:54 UTC, Henryws commented
Remove the wine pacscript from this PR, other than that, looks good.

2022-03-20 22:04 UTC, Henryws commented on packages/bottles-v1-deb/bottles-v1-deb.pacscript
> +gives="bottles-v1"
`gives` does not utilize the actual deb name, which is `com.github.mirkobrombin.bottles`

2022-03-20 22:10 UTC, Henryws requested changes

2022-03-20 22:10 UTC, Henryws commented on packages/bottles-v1-deb/bottles-v1-deb.pacscript
> +gives="bottles-v1 com.github.mirkobrombin.bottles bottles"
`gives` can only have one key in it, so remove `bottles-v1`

2022-03-20 23:50 UTC, cat-master21 commented
Name of the deb is different then bottles-v1-deb which Pacstall can't take.

2022-03-20 23:50 UTC, closed without merging