upd(alacritty): `0.10.0` -> `0.10.1`
pacstall/pacstall-programs pull request #814
Opened 2022-03-06 11:10 UTC by warofzen

2022-03-07 13:57 UTC, wizard-28 reviewed
@kaistian do you wish to continue maintaining this pacscript?

2022-03-07 13:58 UTC, wizard-28 commented
@Henryws the compilation failed due to a `rustc` error.

2022-03-07 14:07 UTC, wizard-28 reviewed
@warofzen do you wish to maintain this pacscript?

2022-03-07 14:58 UTC, warofzen commented
> @warofzen do you wish to maintain this pacscript?

Yeah, sure.

2022-03-08 00:19 UTC, Henryws commented
> @Henryws the compilation failed due to a `rustc` error.

Narrowed it down to a cargo version issue. Installing with rustup works fine on debian stable, but the current ubuntu docker works fine ootb.

2022-03-08 07:56 UTC, wizard-28 commented
> > @Henryws the compilation failed due to a `rustc` error.
> 
> Narrowed it down to a cargo version issue. Installing with rustup works fine on debian stable, and the current ubuntu docker works fine ootb.

Yeah... so what to do here?

2022-03-08 23:40 UTC, Henryws commented
As I've said on discord, if it doesn't work on debian but it does on Ubuntu, we should merge, as we technically only support Ubuntu, and debian support is taken with a grain of salt.

2022-03-10 08:06 UTC, wizard-28 requested changes

2022-03-10 08:06 UTC, wizard-28 commented on packages/alacritty/alacritty.pacscript
>  name="alacritty"
```suggestion
if [[ "$(grep -Po 'ID=\K[^"]+' /etc/os-release)" == "debian" ]]; then
    fancy_message error "This script doesn't work on Debian"
    cleanup # Trigger pacstall cleanups
    exit 1
fi

name="alacritty"
```

Block installation on Debian.

2022-03-11 08:52 UTC, wizard-28 approved these changes

2022-03-11 08:52 UTC, merged