upd(nyxt-deb): `2.1.1` -> `2.2.4`
pacstall/pacstall-programs pull request #820
Opened 2022-03-07 00:49 UTC by cat-master21

2022-03-07 13:50 UTC, wizard-28 requested changes
@WRM-42 do you wish to continue maintaining this pacscript?

2022-03-07 17:17 UTC, WRM-42 commented
@wizard-28 No

2022-03-08 08:08 UTC, wizard-28 requested changes
@cat-master21 replace @WRM-42 as the maintainer, if you're willing to maintain this script.

2022-03-10 08:09 UTC, wizard-28 approved these changes

2022-03-10 08:09 UTC, merged