upd(balena-etcher-electron-deb): `1.7.3` -> `1.7.7`
pacstall/pacstall-programs pull request #821
Opened 2022-03-07 01:45 UTC by cat-master21

2022-03-07 13:48 UTC, wizard-28 requested changes
@kwon37xi do you wish to continue to maintain this pacscript?

2022-03-10 05:41 UTC, kwon37xi commented
No, not anymore. 
thank you.

2022-03-10 08:14 UTC, wizard-28 requested changes
@cat-master21 replace @kwon37xi as the maintainer.

2022-03-11 08:47 UTC, wizard-28 approved these changes

2022-03-11 08:48 UTC, merged