upd(webapp-manager-deb): `1.1.5` -> `1.1.9`
pacstall/pacstall-programs pull request #826
Opened 2022-03-09 03:05 UTC by cat-master21

2022-03-10 08:07 UTC, wizard-28 reviewed
@Korkmatik do you wish to continue maintaining this pacscript?

2022-03-12 17:21 UTC, Korkmatik commented
@wizard-28 No I do not want to maintain it anymore

2022-03-16 00:48 UTC, cat-master21 commented
Not sure what the Ci's issue is.

2022-03-17 09:24 UTC, wizard-28 requested changes

2022-03-17 09:24 UTC, wizard-28 commented on packages/webapp-manager-deb/webapp-manager-deb.pacscript
> +repology="webapp-manager"
```suggestion
repology=("project: webapp-manager")
```

2022-03-19 06:33 UTC, wizard-28 approved these changes

2022-03-19 06:59 UTC, merged

2022-03-24 14:42 UTC, Zahrun commented
@cat-master21 , I think the https address is not reachable. Should be replaced by http.

2022-03-25 14:32 UTC, cat-master21 commented
Your right, @Zahrun I'll fix this soon.