upd(element-desktop-deb): `1.10.4` -> `1.10.6`
pacstall/pacstall-programs pull request #829
Opened 2022-03-11 02:27 UTC by cat-master21

Notice that I needed to change the gives because:

`pumpkinking@pumpkinking-desktop:~$ pacstall -Up

[sudo] password for pumpkinking: 
[+] INFO: Checking for updates
[+] INFO: Packages can be upgraded
Upgradable: 2
	element-desktop-deb @ pacstall/pacstall-programs 
	github-desktop @ pacstall/pacstall-programs 

Do you want to upgrade element-desktop-deb? [Y/n] y
Do you want to view/edit the pacscript [y/N] n
[+] INFO: Sourcing pacscript
[+] INFO: URL exists
[!] ERROR: element-desktop-deb breaks element-desktop, which is currently installed by apt
[+] INFO: Cleaning up
Do you want to upgrade github-desktop? [Y/n] y
`

2022-03-11 03:01 UTC, Henryws requested changes

2022-03-11 03:01 UTC, Henryws commented on packages/element-desktop-deb/element-desktop-deb.pacscript
> +breaks="$element-desktop-deb ${gives}-git ${gives}-bin ${gives}-app"
`$element-desktop-deb` is not a variable

2022-03-11 03:01 UTC, Henryws requested changes

2022-03-11 03:01 UTC, Henryws commented on packages/element-desktop-deb/element-desktop-deb.pacscript
> +gives="element-desktop-deb"
gives should be `element-desktop`

2022-03-11 08:53 UTC, wizard-28 submitted a review, later dismissed

2022-03-11 22:15 UTC, Henryws requested changes

2022-03-14 00:46 UTC, cat-master21 commented on packages/element-desktop-deb/element-desktop-deb.pacscript
> +breaks="element-desktop ${gives}-git ${gives}-bin ${gives}-app"
If I do that updating will fail!

2022-03-14 00:52 UTC, Henryws commented on packages/element-desktop-deb/element-desktop-deb.pacscript
> +breaks="element-desktop ${gives}-git ${gives}-bin ${gives}-app"
Ok, then add it to `replace`

2022-03-16 02:45 UTC, cat-master21 commented
Ready for review @Henryws

2022-03-17 10:14 UTC, wizard-28 requested changes

2022-03-17 10:14 UTC, wizard-28 commented on packages/element-desktop-deb/element-desktop-deb.pacscript
> +repology="element-desktop"
```suggestion
repology=("project: element-desktop")
```

2022-03-19 07:02 UTC, wizard-28 approved these changes

2022-03-19 07:06 UTC, merged