Wine staging git
pacstall/pacstall-programs pull request #83
Opened 2021-07-25 18:16 UTC by rain1598

2021-07-26 08:51 UTC, wizard-28 requested changes

2021-07-26 08:51 UTC, wizard-28 commented on packages/wine-staging-git/wine-staging-git.pacscript
> +        make
```suggestion
        make -j$(nproc)
```

2021-07-26 08:51 UTC, wizard-28 commented on packages/wine-staging-git/wine-staging-git.pacscript
> +        make
```suggestion
        make -j$(nproc)
```

2021-07-27 20:26 UTC, D-Brox commented
To be re-tested after 1.6 release due to install issues

2021-07-27 22:11 UTC, rain1598 commented
> To be re-tested after 1.6 release due to install issues

what went wrong during install?

2021-07-28 01:00 UTC, D-Brox commented
> > To be re-tested after 1.6 release due to install issues
> 
> what went wrong during install?

`mkdir` without sudo only works with fakeroot, on 1.6

2021-07-28 01:05 UTC, rain1598 commented
I'll just chown it manually

2021-07-28 15:29 UTC, rain1598 commented
nvm chown doesn't work

2021-08-12 16:36 UTC, merged