upd(brave): switch maintainers and update packages
pacstall/pacstall-programs pull request #831
Opened 2022-03-11 21:51 UTC by Henryws

I've decided to start maintaining Brave, as the previous maintainers have stepped down from doing so.

2022-03-12 03:59 UTC, WRM-42 commented
I don't have any plans to stop maintaining them any time soon. I will try to organize myself to find more free time, as these pacscripts are quickly becoming outdated.

2022-03-12 04:53 UTC, wizard-28 commented
> I don't have any plans to stop maintaining them any time soon. I will try to organize myself to find more free time, as these pacscripts are quickly becoming outdated.

Well, we're brewing a tool to make maintainers' lives easier. It's not done yet, but the repository is https://github.com/pacstall/pacup. You can join our discord/matrix if you want to participate in it's development before I push the commits to github.

2022-03-12 04:55 UTC, wizard-28 commented
> I've decided to start maintaining Brave, as the previous maintainers have stepped down from doing so.
> 
> @WRM-42 do you want to continue maintaining certain Brave Pacscripts?

Tagging @Zahrun as he maintains some of those pacscripts.

2022-03-15 17:00 UTC, Zahrun commented
I’m not planning to maintain actively the brave-deb pacscript.
I find it confusing that we cannot subscribe to only the stable releases for brave.
At least I didn’t find a way.
Thank you

2022-03-17 10:56 UTC, wizard-28 requested changes
@Henryws do the repology thingy

2022-03-20 07:03 UTC, wizard-28 requested changes
Check for updates in all of the pacscripts here.

2022-03-20 07:03 UTC, wizard-28 commented on packages/brave-browser-nightly-deb/brave-browser-nightly-deb.pacscript
> +repology=("project: brave" "visiblename: brave-nightly-bin")
You might want to Scoop for nightly, they have the latest one

![img](http://0x0.st/oN1r.png)

```suggestion
repology=("project: brave" "visiblename: brave-nightly")
```

2022-03-21 06:27 UTC, wizard-28 commented on packages/brave-browser-nightly-deb/brave-browser-nightly-deb.pacscript
> +repology=("project: brave" "visiblename: brave-nightly-bin")
@Henryws your thoughts?

2022-03-24 05:38 UTC, wizard-28 requested changes
Update all of them. They're outdated.

2022-03-25 06:16 UTC, wizard-28 approved these changes

2022-03-25 06:21 UTC, merged