upd(opentoonz): `1.5.0` -> `1.6.0rc`
pacstall/pacstall-programs pull request #843
Opened 2022-03-14 21:49 UTC by echometerain

2022-03-15 16:53 UTC, wizard-28 requested changes
The CI fails

2022-03-27 05:17 UTC, wizard-28 commented
@echometerain status on this?

2022-04-08 20:54 UTC, echometerain commented
@wizard-28 all checks except debian testing is successful
and pacstall is a package manager for ubuntu

2022-04-09 14:49 UTC, Henryws requested changes
```
install: target '/usr/src/pacstall/opentoonz/usr/share/applications/' is not a directory: No such file or directory
install: target '/usr/src/pacstall/opentoonz/usr/share/pixmaps/' is not a directory: No such file or directory
```

2022-04-10 16:54 UTC, Henryws requested changes

2022-04-10 16:54 UTC, Henryws commented on packages/opentoonz/opentoonz.pacscript
> +  sudo mkdir -P "/usr/src/pacstall/opentoonz/usr/share/pixmaps/"
These `mkdir`s should use `-p`. `-P` is not a flag.

2022-04-10 21:08 UTC, echometerain commented
I have no idea why this doesn't work, it runs on my machine perfectly
![image](https://user-images.githubusercontent.com/70437021/162639929-5900b15b-8f45-446a-9cce-963e97778cc0.png)

2022-04-11 04:04 UTC, cat-master21 commented
It's only in Debian stable, and not Sid. For Ubuntu It's only in Impish and Hirsute: https://packages.ubuntu.com/impish/libgsl25. It is not in Ubuntu Devel (Jammy) or Debain Sid so those checks failed.

2022-04-11 04:05 UTC, cat-master21 commented
Libgls27 is in unstable Debian repos: https://packages.debian.org/search?keywords=libgsl27

2022-04-11 04:08 UTC, cat-master21 commented
Try Libgsl-dev, @echometerain https://packages.debian.org/sid/libgsl-dev

2022-04-11 13:33 UTC, echometerain commented
thank you @cat-master21! It works now!

2022-04-11 21:34 UTC, Henryws requested changes

2022-04-11 21:34 UTC, Henryws commented on packages/opentoonz/opentoonz.pacscript
> +  print "#\!/bin/sh\nsh /opt/opentoonz/bin/opentoonz" | sudo tee /usr/bin/opentoonz
```bash
Error: no such file "#\!/bin/sh\nsh /opt/opentoonz/bin/opentoonz"
```

2022-04-11 21:35 UTC, Henryws submitted a review, later dismissed

2022-04-11 21:35 UTC, Henryws commented
Oops misclick

2022-04-12 00:15 UTC, echometerain commented on packages/opentoonz/opentoonz.pacscript
> +  print "#\!/bin/sh\nsh /opt/opentoonz/bin/opentoonz" | sudo tee /usr/bin/opentoonz
lmao zsh moment

2022-04-12 22:31 UTC, Henryws requested changes

2022-04-12 22:31 UTC, Henryws commented on packages/opentoonz/opentoonz.pacscript
> +    sudo rm -rf "home/${LOGNAME}/.config/OpenToonz/"
Shouldn't this have a `/` in front? Also why `sudo`?

2022-04-12 22:34 UTC, Henryws requested changes

2022-04-12 22:34 UTC, Henryws commented on packages/opentoonz/opentoonz.pacscript
> +  printf '#!/bin/sh\nsh /opt/opentoonz/bin/opentoonz' | sudo tee /usr/bin/opentoonz
Redirect `tee` to `/dev/null`

2022-04-12 23:21 UTC, Henryws requested changes

2022-04-12 23:21 UTC, Henryws commented on packages/opentoonz/opentoonz.pacscript
> +  printf '#!/bin/sh\nsh /opt/opentoonz/bin/opentoonz' | sudo tee "/usr/bin/opentoonz" > "/dev/null"
```suggestion
  printf '#!/bin/sh\nsh /opt/opentoonz/bin/opentoonz' | sudo tee /usr/bin/opentoonz > /dev/null
```

2022-04-15 17:24 UTC, Henryws approved these changes

2022-04-15 17:28 UTC, cat-master21 commented
@echometerain use Libgsl-dev: https://packages.ubuntu.com/jammy/libgsl-dev not libgsl25 as it is only in Impish and Hirsuite (Jammy has libgsl27).

2022-04-15 18:44 UTC, echometerain commented
> @echometerain use libgsl-dev: https://packages.ubuntu.com/jammy/libgsl-dev not libgsl25 as it is only in Impish and Hirsuite (Jammy has libgsl27).

I already added it

2022-04-15 21:44 UTC, cat-master21 commented
Whops..Who's... I forgot the comment was from 5 days ago... A bit embarrassing.

2022-04-19 01:31 UTC, Henryws approved these changes

2022-04-19 23:47 UTC, cat-master21 approved these changes

2022-04-20 00:06 UTC, merged