fix(steam-deb): Enable 32 bit support
pacstall/pacstall-programs pull request #862
Opened 2022-03-19 21:17 UTC by WRM-42

Fixes #838

2022-03-20 07:09 UTC, wizard-28 commented
@Henryws handle this. The CI fails due to `i386` errors.

2022-03-23 23:45 UTC, Henryws requested changes

2022-03-23 23:45 UTC, Henryws commented on packages/steam-deb/steam-deb.pacscript
> +    sudo dpkg --add-architecture i386
```suggestion
    sudo dpkg --add-architecture i386
    sudo apt-get update
```

2022-03-24 05:36 UTC, wizard-28 commented
@Henryws ![](https://0x0.st/oNG_.png)

2022-03-26 14:13 UTC, WRM-42 commented
I did a test on a virtual machine and it works well

https://bin.snopyta.org/?8096c735389a0c0c#38hMMR5ef3hx4mVkjVrbToenTtjLdjDCmYXMDNzHPAsW

2022-03-26 14:14 UTC, Henryws commented
> I did a test on a virtual machine and it works well
> 
> [bin.snopyta.org/?8096c735389a0c0c#38hMMR5ef3hx4mVkjVrbToenTtjLdjDCmYXMDNzHPAsW](https://bin.snopyta.org/?8096c735389a0c0c#38hMMR5ef3hx4mVkjVrbToenTtjLdjDCmYXMDNzHPAsW)

Yup, it's an issue with the CI

2022-03-26 15:02 UTC, merged