add: `distrobox`
pacstall/pacstall-programs pull request #863
Opened 2022-03-20 16:56 UTC by cat-master21

2022-03-20 21:14 UTC, cat-master21 commented
I can verify these commands work for me:
![Screenshot](https://user-images.githubusercontent.com/96554164/159186163-4b4fa8b1-1153-42a0-b698-9e92bc69153a.png)
And just to remember Pacstall will link the /usr/bin so distrobox will be $PATH.

2022-03-21 06:31 UTC, wizard-28 requested changes

2022-03-21 06:31 UTC, wizard-28 commented on packages/distrobox/distrobox.pacscript
> +}
```suggestion
}

build() {
  true
}
```

2022-03-21 06:32 UTC, wizard-28 commented
@cat-master21 dependency issue on Ubuntu, check the CI

![](http://0x0.st/oNfA.png)

2022-03-23 21:25 UTC, cat-master21 commented
Thinking about Podman dependency and just time to maintain this.

2022-03-23 21:25 UTC, closed without merging