add: `lyx-deb`
pacstall/pacstall-programs pull request #971
Opened 2022-04-13 18:17 UTC by cat-master21

2022-04-13 23:08 UTC, Henryws requested changes
```
The following packages have unmet dependencies:
 lyx : Depends: libhunspell-1.6-0 but it is not installable
       Recommends: texlive-latex-recommended but it is not going to be installed
       Recommends: texlive-latex-extra but it is not going to be installed
       Recommends: texlive-science but it is not going to be installed
       Recommends: texlive-generic-recommended but it is not installable
       Recommends: texlive-generic-extra but it is not installable
       Recommends: texlive-fonts-recommended but it is not going to be installed
       Recommends: preview-latex-style but it is not going to be installed
       Recommends: dvipng but it is not going to be installed
       Recommends: imagemagick
       Recommends: psutils
       Recommends: ghostscript
       Recommends: poppler-utils
       Recommends: fonts-lyx but it is not going to be installed
       Recommends: evince-gtk but it is not installable or
                   pdf-viewer
       Recommends: elyxer but it is not installable or
                   tex4ht or
                   hevea but it is not going to be installed or
                   tth but it is not going to be installed or
                   latex2html but it is not going to be installed
[!] ERROR: Failed to install the package
```

2022-04-13 23:28 UTC, Henryws requested changes
Errors with
```
The following packages have unmet dependencies:
 lyx : Depends: lyx-common (= 2.3.6.1-1~focal~ppa1) but 2.3.6.1-1~bionic~ppa1 is to be installed
       Recommends: texlive-latex-recommended but it is not going to be installed
       Recommends: texlive-latex-extra but it is not going to be installed
       Recommends: texlive-science but it is not going to be installed
       Recommends: texlive-generic-recommended but it is not installable
       Recommends: texlive-generic-extra but it is not installable
       Recommends: texlive-fonts-recommended but it is not going to be installed
       Recommends: preview-latex-style but it is not going to be installed
       Recommends: dvipng but it is not going to be installed
       Recommends: imagemagick
       Recommends: psutils
       Recommends: ghostscript
       Recommends: poppler-utils
       Recommends: fonts-lyx but it is not going to be installed
       Recommends: evince-gtk but it is not installable or
                   pdf-viewer
       Recommends: elyxer but it is not installable or
                   tex4ht or
                   hevea but it is not going to be installed or
                   tth but it is not going to be installed or
                   latex2html but it is not going to be installed
```

2022-04-14 18:00 UTC, saenai255 commented
Please follow the common PR format for adding packages. Did you contact the devs?

2022-04-14 18:52 UTC, cat-master21 commented
> Please follow the common PR format for adding packages. Did you contact the devs?

Done via email: https://www.lyx.org/MailingLists#toc2

2022-04-14 23:26 UTC, Henryws requested changes

2022-04-14 23:26 UTC, Henryws commented on packages/lyx/lyx.pacscript
> +true
Tab this

2022-04-14 23:28 UTC, Henryws requested changes

2022-04-14 23:28 UTC, Henryws commented on packages/lyx/lyx.pacscript
> +repology=("project: lyx")
Add an line between `repology` and `prepare`

2022-04-14 23:49 UTC, Henryws approved these changes

2022-04-14 23:49 UTC, merged